begin;

-- Separate the health of scheduled/dev-shift executions from the noisier
-- all-day agent digest. A manual-heavy development day can be red while the
-- scheduled shift lane remains safe and boring.

create table if not exists public.catalog_agent_dev_shift_runs (
  id bigint generated by default as identity primary key,
  environment text not null default 'dev'
    check (environment in ('dev')),
  status text not null default 'started'
    check (status in ('started', 'skipped', 'completed', 'failed')),
  skip_reason text,
  request_payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(request_payload) = 'object'),
  guard_snapshot jsonb not null default '{}'::jsonb
    check (jsonb_typeof(guard_snapshot) = 'object'),
  worker_results jsonb not null default '[]'::jsonb
    check (jsonb_typeof(worker_results) = 'array'),
  skipped_workers jsonb not null default '[]'::jsonb
    check (jsonb_typeof(skipped_workers) = 'array'),
  digest_snapshot jsonb not null default '{}'::jsonb
    check (jsonb_typeof(digest_snapshot) = 'object'),
  error_message text,
  duration_ms integer
    check (duration_ms is null or duration_ms >= 0),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_dev_shift_runs_finished_after_started
    check (finished_at is null or finished_at >= started_at)
);

create index if not exists catalog_agent_dev_shift_runs_status_started_idx
  on public.catalog_agent_dev_shift_runs(environment, status, started_at desc);

alter table public.catalog_agent_dev_shift_runs enable row level security;

revoke all on table public.catalog_agent_dev_shift_runs from public, anon, authenticated;
grant select on table public.catalog_agent_dev_shift_runs to authenticated;
grant all on table public.catalog_agent_dev_shift_runs to service_role;

drop policy if exists catalog_agent_dev_shift_runs_catalog_admin_select
on public.catalog_agent_dev_shift_runs;
create policy catalog_agent_dev_shift_runs_catalog_admin_select
on public.catalog_agent_dev_shift_runs
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace view public.catalog_agent_dev_shift_health
with (security_invoker = true)
as
with today as (
  select *
  from public.catalog_agent_dev_shift_runs s
  where s.environment = 'dev'
    and s.started_at >= current_date::timestamptz
    and s.started_at < (current_date + 1)::timestamptz
),
latest as (
  select *
  from public.catalog_agent_dev_shift_runs s
  where s.environment = 'dev'
  order by s.started_at desc
  limit 1
),
counts as (
  select
    count(*)::bigint as total_shift_runs_today,
    count(*) filter (where status = 'completed')::bigint as completed_shift_runs_today,
    count(*) filter (where status = 'skipped')::bigint as skipped_shift_runs_today,
    count(*) filter (where status = 'failed')::bigint as failed_shift_runs_today,
    coalesce(sum(
      case
        when jsonb_typeof(worker_results) = 'array' then jsonb_array_length(worker_results)
        else 0
      end
    ), 0)::bigint as worker_results_today
  from today
)
select
  coalesce(c.total_shift_runs_today, 0)::bigint as total_shift_runs_today,
  coalesce(c.completed_shift_runs_today, 0)::bigint as completed_shift_runs_today,
  coalesce(c.skipped_shift_runs_today, 0)::bigint as skipped_shift_runs_today,
  coalesce(c.failed_shift_runs_today, 0)::bigint as failed_shift_runs_today,
  coalesce(c.worker_results_today, 0)::bigint as worker_results_today,
  l.id as latest_shift_run_id,
  l.status as latest_shift_status,
  l.skip_reason as latest_skip_reason,
  l.duration_ms as latest_duration_ms,
  l.started_at as latest_started_at,
  l.finished_at as latest_finished_at,
  l.guard_snapshot as latest_guard_snapshot,
  l.digest_snapshot as latest_digest_snapshot,
  case
    when coalesce(c.failed_shift_runs_today, 0) > 0 then 'red'
    when l.status = 'started' and l.started_at < now() - interval '15 minutes' then 'yellow'
    when coalesce(c.total_shift_runs_today, 0) = 0 then 'idle'
    else 'green'
  end as shift_health_status,
  case
    when coalesce(c.failed_shift_runs_today, 0) > 0 then 'A dev-shift failed today. Review the shift ledger before enabling any scheduler.'
    when l.status = 'started' and l.started_at < now() - interval '15 minutes' then 'Latest dev-shift appears stale.'
    when coalesce(c.total_shift_runs_today, 0) = 0 then 'No dev-shift runs today.'
    else 'Dev-shift lane is healthy. Any red daily digest may still be caused by manual test history.'
  end as shift_health_message
from counts c
left join latest l on true;

revoke all on public.catalog_agent_dev_shift_health from public, anon;
grant select on public.catalog_agent_dev_shift_health to authenticated, service_role;

comment on table public.catalog_agent_dev_shift_runs is
  'Ledger of dev-only scheduled-autonomy shift executions, separate from all agent runs.';

comment on view public.catalog_agent_dev_shift_health is
  'Admin-console read model for scheduled dev-shift health distinct from the all-day digest.';

commit;
