begin;

-- Generalize the first tomato-specific guardrail into a data-driven meaningful
-- variant policy. The validator should enforce a general rule: identity-bearing
-- variants must not be collapsed into a base ingredient as aliases.

create table if not exists public.catalog_agent_meaningful_variant_guardrails (
  id bigint generated by default as identity primary key,
  policy_key text not null unique,
  base_slug text not null,
  blocked_term_patterns text[] not null,
  example_terms text[] not null default '{}'::text[],
  required_target_policy text not null,
  error_code text not null default 'meaningful_variant_requires_child_target',
  error_message text not null,
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_meaningful_variant_guardrails_patterns_nonempty
    check (cardinality(blocked_term_patterns) > 0)
);

alter table public.catalog_agent_meaningful_variant_guardrails enable row level security;

revoke all on public.catalog_agent_meaningful_variant_guardrails from public, anon, authenticated;
grant select on public.catalog_agent_meaningful_variant_guardrails to authenticated;
grant all on public.catalog_agent_meaningful_variant_guardrails to service_role;

drop policy if exists catalog_agent_meaningful_variant_guardrails_admin_select
on public.catalog_agent_meaningful_variant_guardrails;

create policy catalog_agent_meaningful_variant_guardrails_admin_select
on public.catalog_agent_meaningful_variant_guardrails
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

insert into public.catalog_agent_meaningful_variant_guardrails (
  policy_key,
  base_slug,
  blocked_term_patterns,
  example_terms,
  required_target_policy,
  error_code,
  error_message,
  status
)
values (
  'small_tomato_variants_not_base_tomato',
  'tomato',
  array[
    '(^| )(pomodorini|pomodorino|ciliegini|ciliegino|datterini|datterino)( |$)',
    '(^| )cherry tomato(es)?( |$)'
  ]::text[],
  array['pomodorini', 'pomodorino', 'ciliegini', 'datterini', 'cherry tomatoes']::text[],
  'Target an explicit child variant such as cherry_tomatoes/pomodorini when present; otherwise escalate as a catalog variant gap or human review.',
  'meaningful_variant_requires_child_target',
  'This term is an identity-bearing variant and must target an explicit child variant, not the generic base ingredient.',
  'active'
)
on conflict (policy_key) do update
set
  base_slug = excluded.base_slug,
  blocked_term_patterns = excluded.blocked_term_patterns,
  example_terms = excluded.example_terms,
  required_target_policy = excluded.required_target_policy,
  error_code = excluded.error_code,
  error_message = excluded.error_message,
  status = excluded.status,
  updated_at = now();

create or replace function public.catalog_agent_normalized_guardrail_text(
  p_value text
)
returns text
language sql
immutable
set search_path = public
as $$
  select regexp_replace(
    regexp_replace(
      lower(trim(coalesce(p_value, ''))),
      '[^[:alnum:][:space:]]+',
      ' ',
      'g'
    ),
    '\s+',
    ' ',
    'g'
  );
$$;

create or replace function public.catalog_agent_meaningful_variant_guardrail_error(
  p_alias_text text,
  p_normalized_text text,
  p_target_slug text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_alias_text text := public.catalog_agent_normalized_guardrail_text(p_alias_text);
  v_normalized_text text := public.catalog_agent_normalized_guardrail_text(p_normalized_text);
  v_target_slug text := lower(trim(coalesce(p_target_slug, '')));
  v_policy public.catalog_agent_meaningful_variant_guardrails%rowtype;
  v_pattern text;
begin
  if v_target_slug = '' then
    return null;
  end if;

  for v_policy in
    select *
    from public.catalog_agent_meaningful_variant_guardrails g
    where g.status = 'active'
      and g.base_slug = v_target_slug
    order by g.id
  loop
    foreach v_pattern in array v_policy.blocked_term_patterns
    loop
      if v_alias_text ~ v_pattern or v_normalized_text ~ v_pattern then
        return public.catalog_agent_validation_error(
          v_policy.error_code,
          v_policy.error_message || ' ' || v_policy.required_target_policy,
          'error'
        );
      end if;
    end loop;
  end loop;

  return null;
end;
$$;

-- Backward-compatible wrapper for the first guardrail name. Its implementation
-- is now table-driven; new code should call
-- catalog_agent_meaningful_variant_guardrail_error(...).
create or replace function public.catalog_agent_blocks_base_tomato_alias(
  p_alias_text text,
  p_normalized_text text,
  p_target_slug text
)
returns boolean
language sql
stable
set search_path = public
as $$
  select public.catalog_agent_meaningful_variant_guardrail_error(
    p_alias_text,
    p_normalized_text,
    p_target_slug
  ) is not null;
$$;

revoke all on function public.catalog_agent_normalized_guardrail_text(text) from public;
grant execute on function public.catalog_agent_normalized_guardrail_text(text) to authenticated;
grant execute on function public.catalog_agent_normalized_guardrail_text(text) to service_role;

revoke all on function public.catalog_agent_meaningful_variant_guardrail_error(text, text, text) from public;
grant execute on function public.catalog_agent_meaningful_variant_guardrail_error(text, text, text) to authenticated;
grant execute on function public.catalog_agent_meaningful_variant_guardrail_error(text, text, text) to service_role;

comment on table public.catalog_agent_meaningful_variant_guardrails is
  'Data-driven guardrails that prevent identity-bearing variant terms from being collapsed into generic base ingredients.';

comment on function public.catalog_agent_meaningful_variant_guardrail_error(text, text, text) is
  'Returns a structured validation error when an alias proposal collapses a governed meaningful variant into its base ingredient.';

comment on function public.catalog_agent_blocks_base_tomato_alias(text, text, text) is
  'Backward-compatible wrapper for the first tomato guardrail. Logic is data-driven by catalog_agent_meaningful_variant_guardrails.';

commit;
