begin;

-- Non-mutating training memory built from real Smart Import creator-caption
-- corpora. These rows are advisory work signals for the Catalog Governance
-- Agent; they never create catalog identity, aliases, or learning memory by
-- themselves.

create table if not exists public.catalog_agent_training_signals (
  id bigint generated by default as identity primary key,
  normalized_text text not null check (length(btrim(normalized_text)) > 0),
  source text not null default 'smart_import_real_caption_training',
  training_signal text not null check (
    training_signal in (
      'catalog_alias_candidate',
      'meaningful_variant_candidate',
      'condition_or_state_check',
      'product_form_candidate',
      'compound_identity_candidate',
      'egg_family_candidate'
    )
  ),
  occurrence_count integer not null default 1 check (occurrence_count >= 1),
  example_sources jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'needs_review' check (
    status in ('needs_review', 'accepted', 'implemented', 'rejected', 'superseded')
  ),
  first_observed_at timestamptz not null default now(),
  last_observed_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  reviewer_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_training_signals_unique_signal
    unique (normalized_text, source, training_signal)
);

create index if not exists catalog_agent_training_signals_status_updated_idx
  on public.catalog_agent_training_signals(status, updated_at desc);

create index if not exists catalog_agent_training_signals_text_idx
  on public.catalog_agent_training_signals(normalized_text);

create index if not exists catalog_agent_training_signals_signal_count_idx
  on public.catalog_agent_training_signals(training_signal, occurrence_count desc);

alter table public.catalog_agent_training_signals enable row level security;

revoke all on table public.catalog_agent_training_signals from public, anon, authenticated;
grant select on table public.catalog_agent_training_signals to authenticated;
grant all privileges on table public.catalog_agent_training_signals to service_role;

drop policy if exists catalog_agent_training_signals_catalog_admin_select
  on public.catalog_agent_training_signals;
create policy catalog_agent_training_signals_catalog_admin_select
on public.catalog_agent_training_signals
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace function public.upsert_catalog_agent_training_signal(
  p_normalized_text text,
  p_training_signal text,
  p_occurrence_count integer default 1,
  p_example_sources jsonb default '[]'::jsonb,
  p_source text default 'smart_import_real_caption_training',
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_normalized_text text := regexp_replace(lower(btrim(coalesce(p_normalized_text, ''))), '\s+', ' ', 'g');
  v_source text := regexp_replace(lower(btrim(coalesce(p_source, 'smart_import_real_caption_training'))), '\s+', '_', 'g');
  v_training_signal text := lower(btrim(coalesce(p_training_signal, '')));
  v_occurrence_count integer := greatest(1, coalesce(p_occurrence_count, 1));
  v_example_sources jsonb := coalesce(p_example_sources, '[]'::jsonb);
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_row public.catalog_agent_training_signals%rowtype;
begin
  perform public.assert_catalog_admin(auth.uid());

  if v_normalized_text = '' then
    raise exception 'normalized_text is required';
  end if;

  if jsonb_typeof(v_example_sources) <> 'array' then
    raise exception 'example_sources must be a JSON array';
  end if;

  if jsonb_typeof(v_metadata) <> 'object' then
    raise exception 'metadata must be a JSON object';
  end if;

  insert into public.catalog_agent_training_signals (
    normalized_text,
    source,
    training_signal,
    occurrence_count,
    example_sources,
    metadata,
    status,
    first_observed_at,
    last_observed_at,
    created_by,
    created_at,
    updated_at
  )
  values (
    v_normalized_text,
    v_source,
    v_training_signal,
    v_occurrence_count,
    v_example_sources,
    v_metadata,
    'needs_review',
    v_now,
    v_now,
    auth.uid(),
    v_now,
    v_now
  )
  on conflict (normalized_text, source, training_signal) do update
  set
    occurrence_count = greatest(public.catalog_agent_training_signals.occurrence_count, excluded.occurrence_count),
    example_sources = excluded.example_sources,
    metadata = public.catalog_agent_training_signals.metadata || excluded.metadata,
    status = case
      when public.catalog_agent_training_signals.status in ('implemented', 'accepted') then public.catalog_agent_training_signals.status
      else excluded.status
    end,
    last_observed_at = v_now,
    updated_at = v_now
  returning * into v_row;

  return jsonb_build_object(
    'id', v_row.id,
    'normalized_text', v_row.normalized_text,
    'training_signal', v_row.training_signal,
    'occurrence_count', v_row.occurrence_count,
    'status', v_row.status,
    'source', v_row.source
  );
end;
$$;

create or replace function public.get_catalog_agent_training_signal_context(
  p_normalized_texts text[],
  p_limit_per_term integer default 3
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with requested_terms as (
    select distinct regexp_replace(lower(btrim(term)), '\s+', ' ', 'g') as normalized_text
    from unnest(coalesce(p_normalized_texts, array[]::text[])) as term
    where btrim(coalesce(term, '')) <> ''
  ),
  ranked as (
    select
      s.normalized_text,
      s.training_signal,
      s.occurrence_count,
      s.example_sources,
      s.metadata,
      s.status,
      s.source,
      s.updated_at,
      row_number() over (
        partition by s.normalized_text
        order by
          case s.status
            when 'implemented' then 1
            when 'accepted' then 2
            when 'needs_review' then 3
            else 9
          end,
          s.occurrence_count desc,
          s.updated_at desc
      ) as rn
    from public.catalog_agent_training_signals s
    join requested_terms r
      on r.normalized_text = s.normalized_text
    where s.status in ('needs_review', 'accepted', 'implemented')
  ),
  limited as (
    select *
    from ranked
    where rn <= greatest(1, coalesce(p_limit_per_term, 3))
  ),
  term_map as (
    select
      normalized_text,
      jsonb_agg(
        jsonb_build_object(
          'training_signal', training_signal,
          'occurrence_count', occurrence_count,
          'example_sources', example_sources,
          'metadata', metadata,
          'status', status,
          'source', source,
          'updated_at', updated_at
        )
        order by rn
      ) as signals
    from limited
    group by normalized_text
  )
  select jsonb_build_object(
    'metadata', jsonb_build_object(
      'source', 'catalog_agent_training_signal_context_v1',
      'terms_requested', (select count(*) from requested_terms),
      'terms_with_training_signals', (select count(*) from term_map),
      'included_statuses', jsonb_build_array('implemented', 'accepted', 'needs_review')
    ),
    'runtime_instruction', jsonb_build_object(
      'policy', 'Training signals are advisory corpus evidence. They can influence proposal priority, evidence, and questions, but they are not catalog truth and must not bypass validators.',
      'status_semantics', jsonb_build_object(
        'implemented', 'durable behavior already changed; follow unless current evidence contradicts it',
        'accepted', 'reviewed guidance; strongly prefer it',
        'needs_review', 'unreviewed corpus pattern; use only as caution/evidence'
      )
    ),
    'term_training_signals', coalesce(
      (select jsonb_object_agg(normalized_text, signals) from term_map),
      '{}'::jsonb
    )
  );
$$;

revoke all on function public.upsert_catalog_agent_training_signal(text, text, integer, jsonb, text, jsonb) from public;
grant execute on function public.upsert_catalog_agent_training_signal(text, text, integer, jsonb, text, jsonb) to authenticated;
grant execute on function public.upsert_catalog_agent_training_signal(text, text, integer, jsonb, text, jsonb) to service_role;

revoke all on function public.get_catalog_agent_training_signal_context(text[], integer) from public;
grant execute on function public.get_catalog_agent_training_signal_context(text[], integer) to authenticated;
grant execute on function public.get_catalog_agent_training_signal_context(text[], integer) to service_role;

comment on table public.catalog_agent_training_signals is
  'Non-mutating operational training signals extracted from real Smart Import caption corpora for governed Catalog Agent review.';

comment on function public.upsert_catalog_agent_training_signal(text, text, integer, jsonb, text, jsonb) is
  'Catalog-admin/service-role helper to upsert advisory training signals. Does not mutate catalog identity or learning memory.';

comment on function public.get_catalog_agent_training_signal_context(text[], integer) is
  'Returns compact advisory training-signal context for Catalog Agent work items.';

commit;
