-- Minimal canonical alias model for ingredient matching.
-- Purpose: map observed alias strings to existing canonical produce/basic ingredients.

create table if not exists public.ingredient_aliases (
  id bigint generated by default as identity primary key,
  produce_id text,
  basic_ingredient_id text,
  alias_text text not null,
  normalized_alias_text text not null,
  language_code text,
  source text not null default 'manual',
  confidence double precision check (confidence is null or (confidence >= 0 and confidence <= 1)),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ingredient_aliases_exactly_one_target_check
    check (
      ((case when produce_id is null then 0 else 1 end) +
       (case when basic_ingredient_id is null then 0 else 1 end)) = 1
    ),
  constraint ingredient_aliases_normalized_nonempty_check
    check (length(trim(normalized_alias_text)) > 0),
  constraint ingredient_aliases_alias_nonempty_check
    check (length(trim(alias_text)) > 0)
);

create unique index if not exists ingredient_aliases_unique_active_normalized_alias_idx
  on public.ingredient_aliases(normalized_alias_text)
  where is_active = true;

create index if not exists ingredient_aliases_produce_idx
  on public.ingredient_aliases(produce_id)
  where produce_id is not null;

create index if not exists ingredient_aliases_basic_idx
  on public.ingredient_aliases(basic_ingredient_id)
  where basic_ingredient_id is not null;

create index if not exists ingredient_aliases_language_idx
  on public.ingredient_aliases(language_code);
