begin;

alter table public.catalog_agent_runs
  drop constraint if exists catalog_agent_runs_mode_check;

alter table public.catalog_agent_runs
  add constraint catalog_agent_runs_mode_check
  check (
    mode in (
      'proposal_only',
      'validation',
      'auto_apply',
      'manual_replay',
      'worker_orchestration'
    )
  );

create table if not exists public.catalog_agent_worker_jobs (
  id bigint generated by default as identity primary key,
  agent_run_id bigint references public.catalog_agent_runs(id) on delete set null,
  environment text not null default 'unknown'
    check (environment in ('local', 'dev', 'staging', 'production', 'unknown')),
  worker_name text not null
    check (
      worker_name in (
        'enrichment_draft_batch',
        'reconciliation_preview',
        'low_risk_apply_batch'
      )
    ),
  worker_function text not null check (length(btrim(worker_function)) > 0),
  requested_action text not null default 'run'
    check (
      requested_action in (
        'run',
        'dry_run',
        'preview',
        'validate',
        'apply_low_risk'
      )
    ),
  source_domain text,
  status text not null default 'queued'
    check (
      status in (
        'queued',
        'running',
        'completed',
        'failed',
        'cancelled'
      )
    ),
  risk_ceiling text not null default 'low'
    check (risk_ceiling in ('low', 'medium', 'high', 'critical')),
  item_limit integer not null default 10
    check (item_limit between 1 and 100),
  budget_limit_usd numeric(12, 6)
    check (budget_limit_usd is null or budget_limit_usd >= 0),
  dry_run boolean not null default true,
  request_payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(request_payload) = 'object'),
  started_at timestamptz,
  finished_at timestamptz,
  summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(summary) = 'object'),
  failure_reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_worker_jobs_finished_after_started
    check (finished_at is null or started_at is null or finished_at >= started_at)
);

create index if not exists catalog_agent_worker_jobs_run_created_idx
  on public.catalog_agent_worker_jobs(agent_run_id, created_at desc)
  where agent_run_id is not null;

create index if not exists catalog_agent_worker_jobs_status_created_idx
  on public.catalog_agent_worker_jobs(status, created_at desc);

create index if not exists catalog_agent_worker_jobs_worker_status_idx
  on public.catalog_agent_worker_jobs(worker_name, status, created_at desc);

create table if not exists public.catalog_ai_usage_events (
  id bigint generated by default as identity primary key,
  environment text not null default 'unknown'
    check (environment in ('local', 'dev', 'staging', 'production', 'unknown')),
  function_name text not null check (length(btrim(function_name)) > 0),
  request_id text,
  agent_run_id bigint references public.catalog_agent_runs(id) on delete set null,
  worker_job_id bigint references public.catalog_agent_worker_jobs(id) on delete set null,
  model text,
  status text not null
    check (status in ('success', 'fallback', 'error', 'skipped')),
  provider_duration_ms integer
    check (provider_duration_ms is null or provider_duration_ms >= 0),
  input_tokens integer
    check (input_tokens is null or input_tokens >= 0),
  output_tokens integer
    check (output_tokens is null or output_tokens >= 0),
  total_tokens integer
    check (total_tokens is null or total_tokens >= 0),
  estimated_cost_usd numeric(12, 6)
    check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  reason text,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists catalog_ai_usage_events_created_idx
  on public.catalog_ai_usage_events(created_at desc);

create index if not exists catalog_ai_usage_events_agent_run_idx
  on public.catalog_ai_usage_events(agent_run_id, created_at desc)
  where agent_run_id is not null;

create index if not exists catalog_ai_usage_events_worker_job_idx
  on public.catalog_ai_usage_events(worker_job_id, created_at desc)
  where worker_job_id is not null;

alter table public.catalog_agent_worker_jobs enable row level security;
alter table public.catalog_ai_usage_events enable row level security;

revoke all on table public.catalog_agent_worker_jobs from public, anon, authenticated;
revoke all on table public.catalog_ai_usage_events from public, anon, authenticated;

grant select on table public.catalog_agent_worker_jobs to authenticated;
grant select on table public.catalog_ai_usage_events to authenticated;

grant all on table public.catalog_agent_worker_jobs to service_role;
grant all on table public.catalog_ai_usage_events to service_role;

drop policy if exists catalog_agent_worker_jobs_catalog_admin_select
on public.catalog_agent_worker_jobs;
create policy catalog_agent_worker_jobs_catalog_admin_select
on public.catalog_agent_worker_jobs
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

drop policy if exists catalog_ai_usage_events_catalog_admin_select
on public.catalog_ai_usage_events;
create policy catalog_ai_usage_events_catalog_admin_select
on public.catalog_ai_usage_events
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace function public.create_catalog_agent_worker_job(
  p_agent_run_id bigint,
  p_worker_name text,
  p_requested_action text default 'run',
  p_source_domain text default null,
  p_risk_ceiling text default 'low',
  p_item_limit integer default 10,
  p_budget_limit_usd numeric default null,
  p_dry_run boolean default true,
  p_request_payload jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  agent_run_id bigint,
  worker_name text,
  worker_function text,
  requested_action text,
  status text,
  item_limit integer,
  dry_run boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_worker_name text := lower(btrim(coalesce(p_worker_name, '')));
  v_requested_action text := lower(btrim(coalesce(p_requested_action, 'run')));
  v_risk_ceiling text := lower(btrim(coalesce(p_risk_ceiling, 'low')));
  v_item_limit integer := greatest(1, least(100, coalesce(p_item_limit, 10)));
  v_worker_function text;
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  if v_worker_name = 'enrichment_draft_batch' then
    v_worker_function := 'run-catalog-enrichment-draft-batch';
  elsif v_worker_name = 'reconciliation_preview' then
    v_worker_function := 'recipe-reconciliation-preview';
  elsif v_worker_name = 'low_risk_apply_batch' then
    v_worker_function := 'catalog-low-risk-apply-batch';
  else
    raise exception 'unsupported_worker_name: %', p_worker_name
      using errcode = '22023';
  end if;

  if v_requested_action not in ('run', 'dry_run', 'preview', 'validate', 'apply_low_risk') then
    raise exception 'unsupported_requested_action: %', p_requested_action
      using errcode = '22023';
  end if;

  if v_risk_ceiling not in ('low', 'medium', 'high', 'critical') then
    raise exception 'unsupported_risk_ceiling: %', p_risk_ceiling
      using errcode = '22023';
  end if;

  return query
  insert into public.catalog_agent_worker_jobs (
    agent_run_id,
    environment,
    worker_name,
    worker_function,
    requested_action,
    source_domain,
    risk_ceiling,
    item_limit,
    budget_limit_usd,
    dry_run,
    request_payload,
    created_by,
    created_at,
    updated_at
  )
  values (
    p_agent_run_id,
    'dev',
    v_worker_name,
    v_worker_function,
    v_requested_action,
    nullif(btrim(coalesce(p_source_domain, '')), ''),
    v_risk_ceiling,
    v_item_limit,
    p_budget_limit_usd,
    coalesce(p_dry_run, true),
    coalesce(p_request_payload, '{}'::jsonb),
    v_user,
    now(),
    now()
  )
  returning
    catalog_agent_worker_jobs.id,
    catalog_agent_worker_jobs.agent_run_id,
    catalog_agent_worker_jobs.worker_name,
    catalog_agent_worker_jobs.worker_function,
    catalog_agent_worker_jobs.requested_action,
    catalog_agent_worker_jobs.status,
    catalog_agent_worker_jobs.item_limit,
    catalog_agent_worker_jobs.dry_run;
end;
$$;

create or replace function public.start_catalog_agent_worker_job(
  p_job_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_job public.catalog_agent_worker_jobs%rowtype;
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  update public.catalog_agent_worker_jobs j
  set
    status = 'running',
    started_at = coalesce(j.started_at, now()),
    updated_at = now()
  where j.id = p_job_id
    and j.status = 'queued'
  returning * into v_job;

  if not found then
    select * into v_job
    from public.catalog_agent_worker_jobs j
    where j.id = p_job_id;

    if not found then
      raise exception 'catalog_agent_worker_job_not_found: %', p_job_id
        using errcode = 'P0002';
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'job_id', v_job.id,
    'status', v_job.status
  );
end;
$$;

create or replace function public.complete_catalog_agent_worker_job(
  p_job_id bigint,
  p_summary jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_job public.catalog_agent_worker_jobs%rowtype;
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  update public.catalog_agent_worker_jobs j
  set
    status = 'completed',
    finished_at = now(),
    summary = coalesce(p_summary, '{}'::jsonb),
    updated_at = now()
  where j.id = p_job_id
  returning * into v_job;

  if not found then
    raise exception 'catalog_agent_worker_job_not_found: %', p_job_id
      using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'ok', true,
    'job_id', v_job.id,
    'status', v_job.status
  );
end;
$$;

create or replace function public.fail_catalog_agent_worker_job(
  p_job_id bigint,
  p_failure_reason text,
  p_summary jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_job public.catalog_agent_worker_jobs%rowtype;
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  update public.catalog_agent_worker_jobs j
  set
    status = 'failed',
    finished_at = now(),
    failure_reason = nullif(btrim(coalesce(p_failure_reason, '')), ''),
    summary = coalesce(p_summary, '{}'::jsonb),
    updated_at = now()
  where j.id = p_job_id
  returning * into v_job;

  if not found then
    raise exception 'catalog_agent_worker_job_not_found: %', p_job_id
      using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'ok', true,
    'job_id', v_job.id,
    'status', v_job.status
  );
end;
$$;

create or replace view public.catalog_agent_daily_automation_summary
with (security_invoker = true)
as
with days as (
  select date_trunc('day', created_at)::date as day from public.catalog_agent_runs
  union
  select date_trunc('day', created_at)::date as day from public.catalog_agent_worker_jobs
  union
  select date_trunc('day', created_at)::date as day from public.catalog_ai_usage_events
),
run_counts as (
  select
    date_trunc('day', created_at)::date as day,
    count(*)::bigint as agent_runs
  from public.catalog_agent_runs
  group by 1
),
worker_counts as (
  select
    date_trunc('day', created_at)::date as day,
    count(*)::bigint as worker_jobs,
    count(*) filter (where status = 'completed')::bigint as completed_worker_jobs,
    count(*) filter (where status = 'failed')::bigint as failed_worker_jobs
  from public.catalog_agent_worker_jobs
  group by 1
),
usage_counts as (
  select
    date_trunc('day', created_at)::date as day,
    coalesce(sum(input_tokens), 0)::bigint as input_tokens,
    coalesce(sum(output_tokens), 0)::bigint as output_tokens,
    coalesce(sum(total_tokens), 0)::bigint as total_tokens,
    coalesce(sum(estimated_cost_usd), 0)::numeric(12, 6) as estimated_cost_usd
  from public.catalog_ai_usage_events
  group by 1
)
select
  d.day,
  coalesce(r.agent_runs, 0)::bigint as agent_runs,
  coalesce(w.worker_jobs, 0)::bigint as worker_jobs,
  coalesce(w.completed_worker_jobs, 0)::bigint as completed_worker_jobs,
  coalesce(w.failed_worker_jobs, 0)::bigint as failed_worker_jobs,
  coalesce(u.input_tokens, 0)::bigint as input_tokens,
  coalesce(u.output_tokens, 0)::bigint as output_tokens,
  coalesce(u.total_tokens, 0)::bigint as total_tokens,
  coalesce(u.estimated_cost_usd, 0)::numeric(12, 6) as estimated_cost_usd
from days d
left join run_counts r on r.day = d.day
left join worker_counts w on w.day = d.day
left join usage_counts u on u.day = d.day;

revoke all on function public.create_catalog_agent_worker_job(bigint, text, text, text, text, integer, numeric, boolean, jsonb) from public, anon;
grant execute on function public.create_catalog_agent_worker_job(bigint, text, text, text, text, integer, numeric, boolean, jsonb) to authenticated, service_role;

revoke all on function public.start_catalog_agent_worker_job(bigint) from public, anon;
grant execute on function public.start_catalog_agent_worker_job(bigint) to authenticated, service_role;

revoke all on function public.complete_catalog_agent_worker_job(bigint, jsonb) from public, anon;
grant execute on function public.complete_catalog_agent_worker_job(bigint, jsonb) to authenticated, service_role;

revoke all on function public.fail_catalog_agent_worker_job(bigint, text, jsonb) from public, anon;
grant execute on function public.fail_catalog_agent_worker_job(bigint, text, jsonb) to authenticated, service_role;

revoke all on public.catalog_agent_daily_automation_summary from public, anon;
grant select on public.catalog_agent_daily_automation_summary to authenticated, service_role;

comment on table public.catalog_agent_worker_jobs is
  'Manager-level ledger of bounded Autopilot worker jobs authorized by the Catalog Governance Agent.';

comment on table public.catalog_ai_usage_events is
  'Central AI/LLM usage ledger for catalog agent and Autopilot worker calls.';

comment on view public.catalog_agent_daily_automation_summary is
  'Daily rollup for catalog agent runs, delegated worker jobs, and AI usage.';

commit;
