-- Promote only the pending validated enrichment drafts that the resolution plan
-- classifies as safe for creation. This is intentionally narrow: the data patch
-- below applies only to current Giallo Zafferano unresolved terms.

create table if not exists public.catalog_draft_auto_promotion_audit (
  id bigint generated by default as identity primary key,
  batch_id uuid not null,
  normalized_text text not null,
  previous_status text,
  promoted_status text,
  suggested_action text,
  confidence_score double precision,
  result_status text not null,
  detail text,
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists idx_catalog_draft_auto_promotion_audit_created_at
  on public.catalog_draft_auto_promotion_audit(created_at desc);

create index if not exists idx_catalog_draft_auto_promotion_audit_result_status
  on public.catalog_draft_auto_promotion_audit(result_status);

alter table public.catalog_draft_auto_promotion_audit enable row level security;

revoke all on public.catalog_draft_auto_promotion_audit from public, anon, authenticated;
grant all on public.catalog_draft_auto_promotion_audit to service_role;

create or replace function public.promote_pending_validated_catalog_drafts(
  p_limit integer default 25,
  p_normalized_texts text[] default null,
  p_dry_run boolean default true
)
returns table (
  batch_id uuid,
  normalized_text text,
  previous_status text,
  promoted_status text,
  suggested_action text,
  confidence_score double precision,
  applied boolean,
  detail text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_batch_id uuid := gen_random_uuid();
  v_limit integer := greatest(1, least(coalesce(p_limit, 25), 250));
  r record;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  for r in
    select
      p.normalized_text,
      d.status as previous_status,
      p.suggested_action,
      p.confidence_score
    from public.catalog_pending_validated_draft_resolution_plan p
    join public.catalog_ingredient_enrichment_drafts d
      on d.normalized_text = p.normalized_text
    where p.suggested_action = 'promote_to_ready_for_creation'
      and d.status = 'pending'
      and coalesce(d.validated_ready, false)
      and coalesce(array_length(p.ready_validation_errors, 1), 0) = 0
      and coalesce(p.confidence_score, 0) >= 0.9
      and (
        p_normalized_texts is null
        or cardinality(p_normalized_texts) = 0
        or p.normalized_text = any(p_normalized_texts)
      )
    order by p.confidence_score desc, p.occurrence_count desc, p.normalized_text asc
    limit v_limit
  loop
    if not coalesce(p_dry_run, true) then
      update public.catalog_ingredient_enrichment_drafts as d
      set
        status = 'ready',
        needs_manual_review = false,
        reviewer_note = coalesce(
          nullif(trim(d.reviewer_note), '') || E'\n',
          ''
        ) || 'auto_promoted_from_pending_validated_resolution_plan',
        validated_ready = true,
        validated_errors = '[]'::jsonb,
        last_validated_at = now(),
        updated_by = v_user,
        updated_at = now()
      where d.normalized_text = r.normalized_text
        and d.status = 'pending';

      insert into public.catalog_draft_auto_promotion_audit (
        batch_id,
        normalized_text,
        previous_status,
        promoted_status,
        suggested_action,
        confidence_score,
        result_status,
        detail,
        actor_user_id
      )
      values (
        v_batch_id,
        r.normalized_text,
        r.previous_status,
        'ready',
        r.suggested_action,
        r.confidence_score,
        'promoted',
        'auto_promoted_from_pending_validated_resolution_plan',
        v_user
      );
    end if;

    batch_id := v_batch_id;
    normalized_text := r.normalized_text;
    previous_status := r.previous_status;
    promoted_status := case when coalesce(p_dry_run, true) then r.previous_status else 'ready' end;
    suggested_action := r.suggested_action;
    confidence_score := r.confidence_score;
    applied := not coalesce(p_dry_run, true);
    detail := case
      when coalesce(p_dry_run, true) then 'dry_run'
      else 'promoted_to_ready'
    end;
    return next;
  end loop;
end;
$$;

revoke all on function public.promote_pending_validated_catalog_drafts(integer, text[], boolean) from public;
grant execute on function public.promote_pending_validated_catalog_drafts(integer, text[], boolean) to authenticated;
grant execute on function public.promote_pending_validated_catalog_drafts(integer, text[], boolean) to service_role;

do $$
declare
  v_batch_id uuid := gen_random_uuid();
begin
  with giallo_custom_terms as (
    select distinct
      public.normalize_recipe_ingredient_text_for_matching(i.ingredient ->> 'name') as normalized_text
    from public.recipes r
    cross join lateral jsonb_array_elements(coalesce(r.ingredients::jsonb, '[]'::jsonb)) as i(ingredient)
    where r.source_name = 'ricette.giallozafferano.it'
      and nullif(trim(i.ingredient ->> 'ingredient_id'), '') is null
      and nullif(trim(i.ingredient ->> 'produce_id'), '') is null
      and nullif(trim(i.ingredient ->> 'basic_ingredient_id'), '') is null
  ),
  candidates as (
    select
      p.normalized_text,
      d.status as previous_status,
      p.suggested_action,
      p.confidence_score
    from public.catalog_pending_validated_draft_resolution_plan p
    join giallo_custom_terms g
      on g.normalized_text = p.normalized_text
    join public.catalog_ingredient_enrichment_drafts d
      on d.normalized_text = p.normalized_text
    where p.suggested_action = 'promote_to_ready_for_creation'
      and d.status = 'pending'
      and coalesce(d.validated_ready, false)
      and coalesce(array_length(p.ready_validation_errors, 1), 0) = 0
      and coalesce(p.confidence_score, 0) >= 0.9
  ),
  updated as (
    update public.catalog_ingredient_enrichment_drafts as d
    set
      status = 'ready',
      needs_manual_review = false,
      reviewer_note = coalesce(
        nullif(trim(d.reviewer_note), '') || E'\n',
        ''
      ) || 'auto_promoted_from_giallozafferano_safe_resolution_plan',
      validated_ready = true,
      validated_errors = '[]'::jsonb,
      last_validated_at = now(),
      updated_at = now()
    from candidates c
    where d.normalized_text = c.normalized_text
      and d.status = 'pending'
    returning
      d.normalized_text,
      c.previous_status,
      c.suggested_action,
      c.confidence_score
  )
  insert into public.catalog_draft_auto_promotion_audit (
    batch_id,
    normalized_text,
    previous_status,
    promoted_status,
    suggested_action,
    confidence_score,
    result_status,
    detail
  )
  select
    v_batch_id,
    u.normalized_text,
    u.previous_status,
    'ready',
    u.suggested_action,
    u.confidence_score,
    'promoted',
    'auto_promoted_giallozafferano_safe_resolution_plan'
  from updated u;
end;
$$;
