begin;

-- Structured learning memory for the Catalog Governance Agent.
--
-- This turns rejections, validation failures, apply failures, ambiguity, and
-- policy gaps into explicit learning artifacts that future prompts/review
-- workflows can consume. It does not apply catalog changes.

create table if not exists public.catalog_agent_learnings (
  id bigint generated by default as identity primary key,
  proposal_id bigint references public.catalog_agent_proposals(id) on delete set null,
  run_id bigint references public.catalog_agent_runs(id) on delete set null,
  normalized_text text,
  learning_type text not null
    check (
      learning_type in (
        'human_rejection',
        'validator_failure',
        'manual_apply_failure',
        'policy_gap',
        'ambiguity',
        'duplicate_identity_risk',
        'prompt_improvement',
        'catalog_gap',
        'other'
      )
    ),
  severity text not null default 'medium'
    check (severity in ('low', 'medium', 'high', 'critical')),
  status text not null default 'needs_review'
    check (status in ('draft', 'needs_review', 'accepted', 'rejected', 'implemented', 'superseded')),
  original_recommendation jsonb not null default '{}'::jsonb,
  observed_problem text not null,
  corrected_decision text,
  policy_implication text,
  evaluation_recommendation text,
  prompt_recommendation text,
  validator_recommendation text,
  source_event_id bigint references public.catalog_agent_proposal_events(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_learnings_observed_problem_not_blank
    check (length(btrim(observed_problem)) > 0)
);

create index if not exists catalog_agent_learnings_status_created_idx
  on public.catalog_agent_learnings(status, created_at desc);

create index if not exists catalog_agent_learnings_type_status_idx
  on public.catalog_agent_learnings(learning_type, status, severity);

create index if not exists catalog_agent_learnings_normalized_text_idx
  on public.catalog_agent_learnings(normalized_text)
  where normalized_text is not null;

create index if not exists catalog_agent_learnings_proposal_idx
  on public.catalog_agent_learnings(proposal_id)
  where proposal_id is not null;

alter table public.catalog_agent_learnings enable row level security;

revoke all on table public.catalog_agent_learnings from public, anon, authenticated;
grant select on table public.catalog_agent_learnings to authenticated;
grant all on table public.catalog_agent_learnings to service_role;

drop policy if exists catalog_agent_learnings_catalog_admin_select on public.catalog_agent_learnings;
create policy catalog_agent_learnings_catalog_admin_select
on public.catalog_agent_learnings
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace function public.record_catalog_agent_learning(
  p_proposal_id bigint default null,
  p_run_id bigint default null,
  p_learning_type text default 'other',
  p_observed_problem text default null,
  p_severity text default 'medium',
  p_corrected_decision text default null,
  p_policy_implication text default null,
  p_evaluation_recommendation text default null,
  p_prompt_recommendation text default null,
  p_validator_recommendation text default null,
  p_source_event_id bigint default null,
  p_status text default 'needs_review'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_learning_type text := lower(btrim(coalesce(p_learning_type, 'other')));
  v_severity text := lower(btrim(coalesce(p_severity, 'medium')));
  v_status text := lower(btrim(coalesce(p_status, 'needs_review')));
  v_problem text := nullif(btrim(coalesce(p_observed_problem, '')), '');
  v_proposal public.catalog_agent_proposals%rowtype;
  v_run_id bigint := p_run_id;
  v_normalized_text text;
  v_original jsonb := '{}'::jsonb;
  v_learning_id bigint;
begin
  perform public.assert_catalog_admin(v_user);

  if v_learning_type not in (
    'human_rejection',
    'validator_failure',
    'manual_apply_failure',
    'policy_gap',
    'ambiguity',
    'duplicate_identity_risk',
    'prompt_improvement',
    'catalog_gap',
    'other'
  ) then
    v_learning_type := 'other';
  end if;

  if v_severity not in ('low', 'medium', 'high', 'critical') then
    v_severity := 'medium';
  end if;

  if v_status not in ('draft', 'needs_review', 'accepted', 'rejected', 'implemented', 'superseded') then
    v_status := 'needs_review';
  end if;

  if p_proposal_id is not null then
    select *
    into v_proposal
    from public.catalog_agent_proposals p
    where p.id = p_proposal_id;

    if found then
      v_run_id := coalesce(v_run_id, v_proposal.run_id);
      v_normalized_text := v_proposal.normalized_text;
      v_original := jsonb_build_object(
        'proposal_id', v_proposal.id,
        'proposal_type', v_proposal.proposal_type,
        'normalized_text', v_proposal.normalized_text,
        'target_ingredient_id', v_proposal.target_ingredient_id,
        'target_slug', v_proposal.target_slug,
        'proposed_slug', v_proposal.proposed_slug,
        'proposed_alias_text', v_proposal.proposed_alias_text,
        'proposed_localized_name', v_proposal.proposed_localized_name,
        'proposed_language_code', v_proposal.proposed_language_code,
        'confidence_score', v_proposal.confidence_score,
        'risk_level', v_proposal.risk_level,
        'status', v_proposal.status,
        'rationale', v_proposal.rationale,
        'validation_errors', v_proposal.validation_errors
      );
    end if;
  end if;

  if v_problem is null then
    raise exception 'observed_problem_required'
      using errcode = '22023';
  end if;

  insert into public.catalog_agent_learnings (
    proposal_id,
    run_id,
    normalized_text,
    learning_type,
    severity,
    status,
    original_recommendation,
    observed_problem,
    corrected_decision,
    policy_implication,
    evaluation_recommendation,
    prompt_recommendation,
    validator_recommendation,
    source_event_id,
    created_by,
    created_at,
    updated_at
  )
  values (
    p_proposal_id,
    v_run_id,
    v_normalized_text,
    v_learning_type,
    v_severity,
    v_status,
    v_original,
    v_problem,
    nullif(btrim(coalesce(p_corrected_decision, '')), ''),
    nullif(btrim(coalesce(p_policy_implication, '')), ''),
    nullif(btrim(coalesce(p_evaluation_recommendation, '')), ''),
    nullif(btrim(coalesce(p_prompt_recommendation, '')), ''),
    nullif(btrim(coalesce(p_validator_recommendation, '')), ''),
    p_source_event_id,
    v_user,
    now(),
    now()
  )
  returning id into v_learning_id;

  return jsonb_build_object(
    'ok', true,
    'learning_id', v_learning_id,
    'proposal_id', p_proposal_id,
    'run_id', v_run_id,
    'learning_type', v_learning_type,
    'status', v_status
  );
end;
$$;

create or replace function public.get_catalog_agent_learning_memory(
  p_statuses text[] default array['needs_review', 'accepted', 'implemented'],
  p_learning_types text[] default null,
  p_normalized_text text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_statuses text[] := coalesce(p_statuses, array['needs_review', 'accepted', 'implemented']);
  v_learning_types text[] := p_learning_types;
  v_normalized_text text := nullif(lower(btrim(coalesce(p_normalized_text, ''))), '');
  v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_items jsonb := '[]'::jsonb;
  v_total_count bigint := 0;
begin
  perform public.assert_catalog_admin(v_user);

  with filtered as (
    select l.*
    from public.catalog_agent_learnings l
    where (cardinality(v_statuses) = 0 or l.status = any(v_statuses))
      and (v_learning_types is null or cardinality(v_learning_types) = 0 or l.learning_type = any(v_learning_types))
      and (v_normalized_text is null or l.normalized_text = v_normalized_text)
  )
  select count(*) into v_total_count
  from filtered;

  with filtered as (
    select l.*
    from public.catalog_agent_learnings l
    where (cardinality(v_statuses) = 0 or l.status = any(v_statuses))
      and (v_learning_types is null or cardinality(v_learning_types) = 0 or l.learning_type = any(v_learning_types))
      and (v_normalized_text is null or l.normalized_text = v_normalized_text)
  ),
  page as (
    select f.*
    from filtered f
    order by
      case f.severity
        when 'critical' then 0
        when 'high' then 1
        when 'medium' then 2
        when 'low' then 3
        else 9
      end,
      f.created_at desc,
      f.id desc
    limit v_limit
    offset v_offset
  )
  select coalesce(jsonb_agg(to_jsonb(page) order by page.created_at desc, page.id desc), '[]'::jsonb)
  into v_items
  from page;

  return jsonb_build_object(
    'metadata', jsonb_build_object(
      'source', 'catalog_agent_learning_memory_v1',
      'generated_at', now(),
      'limit', v_limit,
      'offset', v_offset,
      'total', v_total_count,
      'filters', jsonb_build_object(
        'statuses', v_statuses,
        'learning_types', v_learning_types,
        'normalized_text', v_normalized_text
      )
    ),
    'items', v_items
  );
end;
$$;

create or replace function public.review_catalog_agent_learning(
  p_learning_id bigint,
  p_status text,
  p_review_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_status text := lower(btrim(coalesce(p_status, '')));
  v_note text := nullif(btrim(coalesce(p_review_note, '')), '');
  v_learning public.catalog_agent_learnings%rowtype;
begin
  perform public.assert_catalog_admin(v_user);

  if v_status not in ('draft', 'needs_review', 'accepted', 'rejected', 'implemented', 'superseded') then
    raise exception 'unsupported_learning_status: %', v_status
      using errcode = '22023';
  end if;

  update public.catalog_agent_learnings l
  set
    status = v_status,
    reviewed_by = v_user,
    reviewed_at = now(),
    policy_implication = case
      when v_note is not null then coalesce(l.policy_implication, '') || case when l.policy_implication is null then '' else E'\n' end || 'Review note: ' || v_note
      else l.policy_implication
    end,
    updated_at = now()
  where l.id = p_learning_id
  returning *
  into v_learning;

  if not found then
    raise exception 'catalog_agent_learning_not_found: %', p_learning_id
      using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'ok', true,
    'learning_id', v_learning.id,
    'status', v_learning.status,
    'reviewed_at', v_learning.reviewed_at
  );
end;
$$;

-- Recreate review RPC so human rejection/more-evidence requests create learning artifacts.
create or replace function public.review_catalog_agent_proposal(
  p_proposal_id bigint,
  p_action text,
  p_reviewer_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_action text := lower(btrim(coalesce(p_action, '')));
  v_note text := nullif(btrim(coalesce(p_reviewer_note, '')), '');
  v_previous_status text;
  v_next_status text;
  v_event_type text;
  v_row public.catalog_agent_proposals%rowtype;
  v_event_id bigint;
  v_learning jsonb;
begin
  perform public.assert_catalog_admin(v_user);

  if p_proposal_id is null then
    raise exception 'proposal_id_required'
      using errcode = '22023';
  end if;

  if v_action not in ('reject', 'defer', 'request_more_evidence', 'queue_for_validation', 'mark_needs_human_review') then
    raise exception 'unsupported_review_action: %', v_action
      using errcode = '22023';
  end if;

  if v_action = 'reject' and v_note is null then
    raise exception 'reviewer_note_required_for_rejection'
      using errcode = '22023';
  end if;

  select *
  into v_row
  from public.catalog_agent_proposals p
  where p.id = p_proposal_id
  for update;

  if not found then
    raise exception 'catalog_agent_proposal_not_found: %', p_proposal_id
      using errcode = 'P0002';
  end if;

  v_previous_status := v_row.status;

  case v_action
    when 'reject' then
      v_next_status := 'rejected';
      v_event_type := 'review_rejected';
    when 'queue_for_validation' then
      v_next_status := 'queued_for_validation';
      v_event_type := 'review_queued_for_validation';
    when 'mark_needs_human_review' then
      v_next_status := 'needs_human_review';
      v_event_type := 'review_marked_needs_human_review';
    when 'request_more_evidence' then
      v_next_status := 'needs_human_review';
      v_event_type := 'review_more_evidence_requested';
    else
      v_next_status := coalesce(v_row.status, 'needs_human_review');
      v_event_type := 'review_deferred';
  end case;

  update public.catalog_agent_proposals p
  set
    status = v_next_status,
    rejection_reason = case
      when v_action = 'reject' then v_note
      else p.rejection_reason
    end,
    updated_at = now()
  where p.id = p_proposal_id
  returning *
  into v_row;

  insert into public.catalog_agent_proposal_events (
    proposal_id,
    run_id,
    event_type,
    event_payload,
    created_by
  )
  values (
    v_row.id,
    v_row.run_id,
    v_event_type,
    jsonb_build_object(
      'action', v_action,
      'previous_status', v_previous_status,
      'next_status', v_next_status,
      'reviewer_note', v_note,
      'mutation_scope', 'proposal_status_only'
    ),
    v_user
  )
  returning id into v_event_id;

  if v_action in ('reject', 'request_more_evidence') then
    v_learning := public.record_catalog_agent_learning(
      p_proposal_id => v_row.id,
      p_run_id => v_row.run_id,
      p_learning_type => case when v_action = 'reject' then 'human_rejection' else 'ambiguity' end,
      p_observed_problem => coalesce(v_note, 'Human review requested more evidence before this proposal can proceed.'),
      p_severity => case when v_action = 'reject' then 'medium' else 'low' end,
      p_corrected_decision => case when v_action = 'reject' then 'Do not apply this proposal as written.' else 'Gather more evidence before validation/apply.' end,
      p_policy_implication => 'Human review outcome should inform future proposal confidence and evidence requirements.',
      p_prompt_recommendation => 'When similar evidence is missing, ask a specific blocking question instead of over-confidently proposing an applyable action.',
      p_source_event_id => v_event_id,
      p_status => 'needs_review'
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'proposal_id', v_row.id,
    'run_id', v_row.run_id,
    'previous_status', v_previous_status,
    'status', v_next_status,
    'event_type', v_event_type,
    'learning', coalesce(v_learning, '{}'::jsonb)
  );
end;
$$;

-- Recreate validator so failed validations become structured learning artifacts.
create or replace function public.validate_catalog_agent_proposal(
  p_proposal_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.catalog_agent_proposals%rowtype;
  v_errors jsonb := '[]'::jsonb;
  v_target public.ingredients%rowtype;
  v_target_from_slug public.ingredients%rowtype;
  v_alias_normalized text;
  v_existing_alias_ingredient_id uuid;
  v_existing_alias_slug text;
  v_existing_localization_ingredient_id uuid;
  v_existing_localization_slug text;
  v_existing_target_localization text;
  v_conflict_slug text;
  v_previous_status text;
  v_next_status text;
  v_event_type text;
  v_event_id bigint;
  v_learning jsonb;
begin
  perform public.assert_catalog_admin(v_user);

  if p_proposal_id is null then
    raise exception 'proposal_id_required'
      using errcode = '22023';
  end if;

  select *
  into v_row
  from public.catalog_agent_proposals p
  where p.id = p_proposal_id
  for update;

  if not found then
    raise exception 'catalog_agent_proposal_not_found: %', p_proposal_id
      using errcode = 'P0002';
  end if;

  v_previous_status := v_row.status;

  if v_previous_status <> 'queued_for_validation' then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('proposal_not_queued_for_validation', 'Proposal must be queued_for_validation before deterministic validation.', 'error'));
  end if;

  if nullif(btrim(coalesce(v_row.normalized_text, '')), '') is null then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('normalized_text_blank', 'normalized_text is required.', 'error'));
  end if;

  if v_row.proposal_type not in ('approve_alias', 'create_canonical', 'add_localization', 'ignore_noise', 'needs_human_review') then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('unsupported_proposal_type', 'Proposal type is not supported by validator v1.', 'error'));
  end if;

  if v_row.risk_level not in ('low', 'medium', 'high', 'critical', 'unknown') then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('unsupported_risk_level', 'risk_level is not supported.', 'error'));
  end if;

  if v_row.confidence_score is not null and (v_row.confidence_score < 0 or v_row.confidence_score > 1) then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('confidence_score_out_of_range', 'confidence_score must be between 0 and 1.', 'error'));
  end if;

  if v_row.auto_apply_eligible and v_row.risk_level <> 'low' then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('auto_apply_requires_low_risk', 'auto_apply_eligible requires low risk.', 'error'));
  end if;

  if nullif(btrim(coalesce(v_row.rationale, '')), '') is null then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('rationale_required', 'A policy rationale is required.', 'error'));
  end if;

  if v_row.target_ingredient_id is not null then
    select * into v_target from public.ingredients i where i.id = v_row.target_ingredient_id;
    if not found then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_ingredient_not_found', 'target_ingredient_id does not exist.', 'error'));
    elsif coalesce(v_target.quality_status, '') <> 'active' then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_ingredient_not_active', 'Target ingredient is not active.', 'error'));
    end if;
  end if;

  if nullif(btrim(coalesce(v_row.target_slug, '')), '') is not null then
    select * into v_target_from_slug from public.ingredients i where i.slug = btrim(v_row.target_slug) limit 1;
    if not found then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_slug_not_found', 'target_slug does not exist.', 'error'));
    elsif coalesce(v_target_from_slug.quality_status, '') <> 'active' then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_slug_not_active', 'target_slug points to a non-active ingredient.', 'error'));
    elsif v_row.target_ingredient_id is not null and v_target_from_slug.id <> v_row.target_ingredient_id then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_id_slug_mismatch', 'target_ingredient_id and target_slug point to different ingredients.', 'error'));
    elsif v_row.target_ingredient_id is null then
      v_target := v_target_from_slug;
    end if;
  end if;

  if v_row.proposal_type in ('approve_alias', 'add_localization') and v_target.id is null then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_required', 'This proposal type requires a valid target ingredient.', 'error'));
  end if;

  if v_row.proposal_type = 'approve_alias' then
    v_alias_normalized := lower(btrim(coalesce(v_row.proposed_alias_text, v_row.normalized_text, '')));
    if nullif(v_alias_normalized, '') is null then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('alias_text_required', 'approve_alias requires proposed_alias_text or normalized_text.', 'error'));
    else
      select a.ingredient_id, i.slug into v_existing_alias_ingredient_id, v_existing_alias_slug
      from public.ingredient_aliases_v2 a
      join public.ingredients i on i.id = a.ingredient_id
      where a.normalized_alias_text = v_alias_normalized
        and coalesce(a.is_active, true)
      order by a.id desc
      limit 1;

      if v_existing_alias_ingredient_id is not null and v_target.id is not null and v_existing_alias_ingredient_id <> v_target.id then
        v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('active_alias_conflict', format('Active alias already points to %s.', v_existing_alias_slug), 'error'));
      end if;

      select l.ingredient_id, i.slug into v_existing_localization_ingredient_id, v_existing_localization_slug
      from public.ingredient_localizations l
      join public.ingredients i on i.id = l.ingredient_id
      where lower(btrim(l.display_name)) = v_alias_normalized
      order by l.updated_at desc
      limit 1;

      if v_existing_localization_ingredient_id is not null and v_target.id is not null and v_existing_localization_ingredient_id <> v_target.id then
        v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('alias_matches_other_localization', format('Alias text matches localization for %s.', v_existing_localization_slug), 'error'));
      end if;
    end if;
  end if;

  if v_row.proposal_type = 'add_localization' then
    if nullif(btrim(coalesce(v_row.proposed_localized_name, '')), '') is null then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('localized_name_required', 'add_localization requires proposed_localized_name.', 'error'));
    end if;

    if nullif(btrim(coalesce(v_row.proposed_language_code, '')), '') is null then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('language_code_required', 'add_localization requires proposed_language_code.', 'error'));
    end if;

    if v_target.id is not null and nullif(btrim(coalesce(v_row.proposed_language_code, '')), '') is not null then
      select l.display_name into v_existing_target_localization
      from public.ingredient_localizations l
      where l.ingredient_id = v_target.id
        and l.language_code = btrim(v_row.proposed_language_code)
      limit 1;

      if v_existing_target_localization is not null and lower(btrim(v_existing_target_localization)) <> lower(btrim(coalesce(v_row.proposed_localized_name, ''))) then
        v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('target_localization_already_exists', 'Target ingredient already has a different localization for this language.', 'error'));
      end if;
    end if;

    if nullif(btrim(coalesce(v_row.proposed_localized_name, '')), '') is not null and nullif(btrim(coalesce(v_row.proposed_language_code, '')), '') is not null then
      select l.ingredient_id, i.slug into v_existing_localization_ingredient_id, v_existing_localization_slug
      from public.ingredient_localizations l
      join public.ingredients i on i.id = l.ingredient_id
      where l.language_code = btrim(v_row.proposed_language_code)
        and lower(btrim(l.display_name)) = lower(btrim(v_row.proposed_localized_name))
      order by l.updated_at desc
      limit 1;

      if v_existing_localization_ingredient_id is not null and v_target.id is not null and v_existing_localization_ingredient_id <> v_target.id then
        v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('localization_conflicts_other_ingredient', format('Localization already belongs to %s.', v_existing_localization_slug), 'error'));
      end if;
    end if;
  end if;

  if v_row.proposal_type = 'create_canonical' then
    if nullif(btrim(coalesce(v_row.proposed_slug, '')), '') is null then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('proposed_slug_required', 'create_canonical requires proposed_slug.', 'error'));
    else
      select i.slug into v_conflict_slug from public.ingredients i where i.slug = btrim(v_row.proposed_slug) limit 1;
      if v_conflict_slug is not null then
        v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('proposed_slug_conflict', 'proposed_slug already exists in ingredients.', 'error'));
      end if;
    end if;

    if nullif(btrim(coalesce(v_row.proposed_localized_name, '')), '') is null then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('canonical_localized_name_required', 'create_canonical requires proposed_localized_name.', 'error'));
    end if;

    if nullif(btrim(coalesce(v_row.proposed_language_code, '')), '') is null then
      v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('canonical_language_code_required', 'create_canonical requires proposed_language_code.', 'error'));
    end if;

    if nullif(btrim(coalesce(v_row.proposed_localized_name, '')), '') is not null and nullif(btrim(coalesce(v_row.proposed_language_code, '')), '') is not null then
      select l.ingredient_id, i.slug into v_existing_localization_ingredient_id, v_existing_localization_slug
      from public.ingredient_localizations l
      join public.ingredients i on i.id = l.ingredient_id
      where l.language_code = btrim(v_row.proposed_language_code)
        and lower(btrim(l.display_name)) = lower(btrim(v_row.proposed_localized_name))
      order by l.updated_at desc
      limit 1;

      if v_existing_localization_ingredient_id is not null then
        v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('canonical_localization_conflict', format('Localized name already belongs to %s.', v_existing_localization_slug), 'error'));
      end if;
    end if;
  end if;

  if v_row.proposal_type = 'needs_human_review' then
    v_errors := v_errors || jsonb_build_array(public.catalog_agent_validation_error('human_review_proposal_not_actionable', 'needs_human_review proposals are triage outcomes and cannot be validated for apply.', 'error'));
  end if;

  if jsonb_array_length(v_errors) = 0 then
    v_next_status := 'validated';
    v_event_type := 'validator_passed';
  else
    v_next_status := 'failed_validation';
    v_event_type := 'validator_failed';
  end if;

  update public.catalog_agent_proposals p
  set
    status = v_next_status,
    validation_errors = v_errors,
    auto_apply_eligible = case when v_next_status = 'validated' and p.risk_level = 'low' then p.auto_apply_eligible else false end,
    updated_at = now()
  where p.id = v_row.id
  returning *
  into v_row;

  insert into public.catalog_agent_proposal_events (
    proposal_id,
    run_id,
    event_type,
    event_payload,
    created_by
  )
  values (
    v_row.id,
    v_row.run_id,
    v_event_type,
    jsonb_build_object(
      'previous_status', v_previous_status,
      'next_status', v_next_status,
      'validation_errors', v_errors,
      'validator_version', 'catalog-agent-validator-v1',
      'mutation_scope', 'proposal_status_only'
    ),
    v_user
  )
  returning id into v_event_id;

  if jsonb_array_length(v_errors) > 0 then
    v_learning := public.record_catalog_agent_learning(
      p_proposal_id => v_row.id,
      p_run_id => v_row.run_id,
      p_learning_type => case
        when v_errors::text like '%human_review_proposal_not_actionable%' then 'ambiguity'
        when v_errors::text like '%conflict%' then 'duplicate_identity_risk'
        else 'validator_failure'
      end,
      p_observed_problem => 'Deterministic validation failed: ' || v_errors::text,
      p_severity => case when v_row.risk_level in ('high', 'critical') then 'high' else 'medium' end,
      p_corrected_decision => 'Do not apply until validation errors are resolved.',
      p_policy_implication => 'Future proposals should avoid this validation failure pattern.',
      p_evaluation_recommendation => 'Add this case to the catalog-agent validation evaluation set.',
      p_prompt_recommendation => 'Ask for missing evidence or use needs_human_review before proposing applyable action.',
      p_validator_recommendation => 'Review whether validator rule should remain strict or needs a documented exception.',
      p_source_event_id => v_event_id,
      p_status => 'needs_review'
    );
  end if;

  return jsonb_build_object(
    'ok', jsonb_array_length(v_errors) = 0,
    'proposal_id', v_row.id,
    'run_id', v_row.run_id,
    'status', v_next_status,
    'validation_errors', v_errors,
    'learning', coalesce(v_learning, '{}'::jsonb)
  );
end;
$$;

-- Recreate apply adapter so apply failures become structured learning artifacts.
create or replace function public.apply_catalog_agent_proposal(
  p_proposal_id bigint,
  p_apply_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.catalog_agent_proposals%rowtype;
  v_note text := nullif(btrim(coalesce(p_apply_note, '')), '');
  v_target_ingredient_id uuid;
  v_alias_text text;
  v_language_code text;
  v_apply_result jsonb := '{}'::jsonb;
  v_event_payload jsonb;
  v_event_id bigint;
begin
  perform public.assert_catalog_admin(v_user);

  if p_proposal_id is null then
    raise exception 'proposal_id_required'
      using errcode = '22023';
  end if;

  select *
  into v_row
  from public.catalog_agent_proposals p
  where p.id = p_proposal_id
  for update;

  if not found then
    raise exception 'catalog_agent_proposal_not_found: %', p_proposal_id
      using errcode = 'P0002';
  end if;

  if v_row.status <> 'validated' then
    raise exception 'proposal_not_validated: status=%', v_row.status
      using errcode = '22023';
  end if;

  if v_row.risk_level <> 'low' then
    raise exception 'manual_apply_v1_requires_low_risk: risk_level=%', v_row.risk_level
      using errcode = '22023';
  end if;

  if v_row.proposal_type not in ('approve_alias', 'add_localization') then
    raise exception 'manual_apply_v1_unsupported_proposal_type: %', v_row.proposal_type
      using errcode = '22023';
  end if;

  v_target_ingredient_id := v_row.target_ingredient_id;
  if v_target_ingredient_id is null and nullif(btrim(coalesce(v_row.target_slug, '')), '') is not null then
    select i.id
    into v_target_ingredient_id
    from public.ingredients i
    where i.slug = btrim(v_row.target_slug)
      and coalesce(i.quality_status, '') = 'active'
    limit 1;
  end if;

  if v_target_ingredient_id is null then
    raise exception 'manual_apply_target_required'
      using errcode = '22023';
  end if;

  if v_row.proposal_type = 'approve_alias' then
    v_alias_text := coalesce(nullif(btrim(coalesce(v_row.proposed_alias_text, '')), ''), nullif(btrim(coalesce(v_row.normalized_text, '')), ''));
    if v_alias_text is null then
      raise exception 'manual_apply_alias_text_required'
        using errcode = '22023';
    end if;

    select to_jsonb(result_row)
    into v_apply_result
    from public.apply_catalog_candidate_decision(
      p_normalized_text => v_row.normalized_text,
      p_action => 'approve_alias',
      p_ingredient_id => v_target_ingredient_id,
      p_alias_text => v_alias_text,
      p_language_code => v_row.proposed_language_code,
      p_confidence_score => v_row.confidence_score,
      p_reviewer_note => coalesce(v_note, 'Applied from validated Catalog Governance Agent proposal.')
    ) as result_row;
  elsif v_row.proposal_type = 'add_localization' then
    v_language_code := coalesce(nullif(btrim(coalesce(v_row.proposed_language_code, '')), ''), 'it');

    if nullif(btrim(coalesce(v_row.proposed_localized_name, '')), '') is null then
      raise exception 'manual_apply_localized_name_required'
        using errcode = '22023';
    end if;

    select to_jsonb(result_row)
    into v_apply_result
    from public.add_ingredient_localization(
      p_ingredient_id => v_target_ingredient_id,
      p_text => v_row.proposed_localized_name,
      p_language_code => v_language_code
    ) as result_row;
  end if;

  v_event_payload := jsonb_build_object(
    'apply_mode', 'manual',
    'proposal_type', v_row.proposal_type,
    'target_ingredient_id', v_target_ingredient_id,
    'apply_note', v_note,
    'apply_result', coalesce(v_apply_result, '{}'::jsonb),
    'mutation_scope', case
      when v_row.proposal_type = 'approve_alias' then 'governed_alias_rpc'
      when v_row.proposal_type = 'add_localization' then 'governed_localization_rpc'
      else 'unknown'
    end
  );

  update public.catalog_agent_proposals p
  set
    status = 'applied',
    applied_at = now(),
    applied_by = v_user,
    updated_at = now()
  where p.id = v_row.id
  returning *
  into v_row;

  insert into public.catalog_agent_proposal_events (
    proposal_id,
    run_id,
    event_type,
    event_payload,
    created_by
  )
  values (
    v_row.id,
    v_row.run_id,
    'manual_apply_succeeded',
    v_event_payload,
    v_user
  );

  return jsonb_build_object(
    'ok', true,
    'proposal_id', v_row.id,
    'run_id', v_row.run_id,
    'status', v_row.status,
    'applied_at', v_row.applied_at,
    'apply_result', coalesce(v_apply_result, '{}'::jsonb)
  );
exception
  when others then
    if v_row.id is not null then
      update public.catalog_agent_proposals p
      set
        validation_errors = coalesce(p.validation_errors, '[]'::jsonb) || jsonb_build_array(
          public.catalog_agent_validation_error('manual_apply_failed', sqlerrm, 'error')
        ),
        updated_at = now()
      where p.id = v_row.id;

      insert into public.catalog_agent_proposal_events (
        proposal_id,
        run_id,
        event_type,
        event_payload,
        created_by
      )
      values (
        v_row.id,
        v_row.run_id,
        'manual_apply_failed',
        jsonb_build_object(
          'error', sqlerrm,
          'sqlstate', sqlstate,
          'apply_mode', 'manual',
          'mutation_scope', 'governed_rpc_only'
        ),
        v_user
      )
      returning id into v_event_id;

      perform public.record_catalog_agent_learning(
        p_proposal_id => v_row.id,
        p_run_id => v_row.run_id,
        p_learning_type => 'manual_apply_failure',
        p_observed_problem => 'Manual apply failed: ' || sqlerrm,
        p_severity => 'high',
        p_corrected_decision => 'Do not retry apply until the governed RPC failure is understood.',
        p_policy_implication => 'Validated proposals may still fail apply; validator or apply preconditions may need tightening.',
        p_evaluation_recommendation => 'Add this apply failure to the manual-apply evaluation set.',
        p_validator_recommendation => 'Consider adding a validator rule for this apply failure.',
        p_source_event_id => v_event_id,
        p_status => 'needs_review'
      );
    end if;

    raise;
end;
$$;

revoke all on function public.record_catalog_agent_learning(bigint, bigint, text, text, text, text, text, text, text, text, bigint, text) from public;
grant execute on function public.record_catalog_agent_learning(bigint, bigint, text, text, text, text, text, text, text, text, bigint, text) to authenticated;
grant execute on function public.record_catalog_agent_learning(bigint, bigint, text, text, text, text, text, text, text, text, bigint, text) to service_role;

revoke all on function public.get_catalog_agent_learning_memory(text[], text[], text, integer, integer) from public;
grant execute on function public.get_catalog_agent_learning_memory(text[], text[], text, integer, integer) to authenticated;
grant execute on function public.get_catalog_agent_learning_memory(text[], text[], text, integer, integer) to service_role;

revoke all on function public.review_catalog_agent_learning(bigint, text, text) from public;
grant execute on function public.review_catalog_agent_learning(bigint, text, text) to authenticated;
grant execute on function public.review_catalog_agent_learning(bigint, text, text) to service_role;

comment on table public.catalog_agent_learnings is
  'Structured continuous-improvement memory for Catalog Governance Agent errors, ambiguity, policy gaps, and review outcomes.';

comment on function public.record_catalog_agent_learning(bigint, bigint, text, text, text, text, text, text, text, text, bigint, text) is
  'Admin-only helper to record structured Catalog Governance Agent learning artifacts.';

comment on function public.get_catalog_agent_learning_memory(text[], text[], text, integer, integer) is
  'Admin-only read contract for Catalog Governance Agent learning memory.';

comment on function public.review_catalog_agent_learning(bigint, text, text) is
  'Admin-only lifecycle transition for Catalog Governance Agent learning artifacts.';

commit;
