begin;

-- Non-mutating external evidence gathered from open, documented food/catalog
-- sources. These rows help the Catalog Governance Agent reason about identity,
-- variants, taxonomy, labels, and nutrients, but they are not catalog truth and
-- never mutate ingredients, aliases, localizations, or recipes by themselves.

create table if not exists public.catalog_agent_external_evidence (
  id bigint generated by default as identity primary key,
  normalized_text text not null check (length(btrim(normalized_text)) > 0),
  source_key text not null check (
    source_key in (
      'usda_fdc',
      'wikidata',
      'foodon',
      'open_food_facts',
      'manual_open_source_review'
    )
  ),
  source_record_id text,
  source_url text,
  source_license text not null,
  source_license_url text,
  evidence_type text not null check (
    evidence_type in (
      'ingredient_identity',
      'variant_identity',
      'synonym_or_label',
      'taxonomy',
      'nutrition',
      'branded_product',
      'packaged_product',
      'not_catalog_identity',
      'ambiguous_identity'
    )
  ),
  trust_level text not null default 'medium' check (trust_level in ('low', 'medium', 'high')),
  confidence_score numeric(4,3) check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1)),
  language_code text,
  canonical_label text,
  aliases jsonb not null default '[]'::jsonb,
  evidence_summary text not null check (length(btrim(evidence_summary)) > 0),
  metadata jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  status text not null default 'needs_review' check (
    status in ('needs_review', 'accepted', 'implemented', 'rejected', 'superseded')
  ),
  first_observed_at timestamptz not null default now(),
  last_observed_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  reviewer_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_external_evidence_aliases_array
    check (jsonb_typeof(aliases) = 'array'),
  constraint catalog_agent_external_evidence_metadata_object
    check (jsonb_typeof(metadata) = 'object'),
  constraint catalog_agent_external_evidence_raw_payload_object
    check (jsonb_typeof(raw_payload) = 'object')
);

create index if not exists catalog_agent_external_evidence_status_updated_idx
  on public.catalog_agent_external_evidence(status, updated_at desc);

create index if not exists catalog_agent_external_evidence_text_idx
  on public.catalog_agent_external_evidence(normalized_text);

create index if not exists catalog_agent_external_evidence_source_type_idx
  on public.catalog_agent_external_evidence(source_key, evidence_type, trust_level);

create unique index if not exists catalog_agent_external_evidence_unique_source_idx
  on public.catalog_agent_external_evidence(
    normalized_text,
    source_key,
    coalesce(source_record_id, ''),
    evidence_type
  );

alter table public.catalog_agent_external_evidence enable row level security;

revoke all on table public.catalog_agent_external_evidence from public, anon, authenticated;
grant select on table public.catalog_agent_external_evidence to authenticated;
grant all privileges on table public.catalog_agent_external_evidence to service_role;
grant usage, select on sequence public.catalog_agent_external_evidence_id_seq to service_role;

drop policy if exists catalog_agent_external_evidence_catalog_admin_select
  on public.catalog_agent_external_evidence;
create policy catalog_agent_external_evidence_catalog_admin_select
on public.catalog_agent_external_evidence
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace function public.upsert_catalog_agent_external_evidence(
  p_normalized_text text,
  p_source_key text,
  p_source_license text,
  p_evidence_type text,
  p_evidence_summary text,
  p_source_record_id text default null,
  p_source_url text default null,
  p_source_license_url text default null,
  p_trust_level text default 'medium',
  p_confidence_score numeric default null,
  p_language_code text default null,
  p_canonical_label text default null,
  p_aliases jsonb default '[]'::jsonb,
  p_metadata jsonb default '{}'::jsonb,
  p_raw_payload jsonb default '{}'::jsonb,
  p_status text default 'needs_review'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_normalized_text text := regexp_replace(lower(btrim(coalesce(p_normalized_text, ''))), '\s+', ' ', 'g');
  v_source_key text := lower(btrim(coalesce(p_source_key, '')));
  v_source_license text := btrim(coalesce(p_source_license, ''));
  v_evidence_type text := lower(btrim(coalesce(p_evidence_type, '')));
  v_evidence_summary text := btrim(coalesce(p_evidence_summary, ''));
  v_source_record_id text := nullif(btrim(coalesce(p_source_record_id, '')), '');
  v_trust_level text := lower(btrim(coalesce(p_trust_level, 'medium')));
  v_status text := lower(btrim(coalesce(p_status, 'needs_review')));
  v_aliases jsonb := coalesce(p_aliases, '[]'::jsonb);
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_raw_payload jsonb := coalesce(p_raw_payload, '{}'::jsonb);
  v_row public.catalog_agent_external_evidence%rowtype;
begin
  perform public.assert_catalog_admin(auth.uid());

  if v_normalized_text = '' then
    raise exception 'normalized_text is required';
  end if;

  if v_source_key not in ('usda_fdc', 'wikidata', 'foodon', 'open_food_facts', 'manual_open_source_review') then
    raise exception 'unsupported_source_key: %', v_source_key;
  end if;

  if v_source_license = '' then
    raise exception 'source_license is required';
  end if;

  if v_evidence_type not in (
    'ingredient_identity',
    'variant_identity',
    'synonym_or_label',
    'taxonomy',
    'nutrition',
    'branded_product',
    'packaged_product',
    'not_catalog_identity',
    'ambiguous_identity'
  ) then
    raise exception 'unsupported_evidence_type: %', v_evidence_type;
  end if;

  if v_trust_level not in ('low', 'medium', 'high') then
    raise exception 'unsupported_trust_level: %', v_trust_level;
  end if;

  if v_status not in ('needs_review', 'accepted', 'implemented', 'rejected', 'superseded') then
    raise exception 'unsupported_status: %', v_status;
  end if;

  if v_evidence_summary = '' then
    raise exception 'evidence_summary is required';
  end if;

  if p_confidence_score is not null and (p_confidence_score < 0 or p_confidence_score > 1) then
    raise exception 'confidence_score must be between 0 and 1';
  end if;

  if jsonb_typeof(v_aliases) <> 'array' then
    raise exception 'aliases must be a JSON array';
  end if;

  if jsonb_typeof(v_metadata) <> 'object' then
    raise exception 'metadata must be a JSON object';
  end if;

  if jsonb_typeof(v_raw_payload) <> 'object' then
    raise exception 'raw_payload must be a JSON object';
  end if;

  insert into public.catalog_agent_external_evidence (
    normalized_text,
    source_key,
    source_record_id,
    source_url,
    source_license,
    source_license_url,
    evidence_type,
    trust_level,
    confidence_score,
    language_code,
    canonical_label,
    aliases,
    evidence_summary,
    metadata,
    raw_payload,
    status,
    first_observed_at,
    last_observed_at,
    created_by,
    created_at,
    updated_at
  )
  values (
    v_normalized_text,
    v_source_key,
    v_source_record_id,
    nullif(btrim(coalesce(p_source_url, '')), ''),
    v_source_license,
    nullif(btrim(coalesce(p_source_license_url, '')), ''),
    v_evidence_type,
    v_trust_level,
    p_confidence_score,
    nullif(lower(btrim(coalesce(p_language_code, ''))), ''),
    nullif(btrim(coalesce(p_canonical_label, '')), ''),
    v_aliases,
    v_evidence_summary,
    v_metadata,
    v_raw_payload,
    v_status,
    v_now,
    v_now,
    auth.uid(),
    v_now,
    v_now
  )
  on conflict (normalized_text, source_key, coalesce(source_record_id, ''), evidence_type) do update
  set
    source_url = excluded.source_url,
    source_license = excluded.source_license,
    source_license_url = excluded.source_license_url,
    trust_level = excluded.trust_level,
    confidence_score = excluded.confidence_score,
    language_code = excluded.language_code,
    canonical_label = excluded.canonical_label,
    aliases = excluded.aliases,
    evidence_summary = excluded.evidence_summary,
    metadata = public.catalog_agent_external_evidence.metadata || excluded.metadata,
    raw_payload = excluded.raw_payload,
    status = case
      when public.catalog_agent_external_evidence.status in ('implemented', 'accepted')
        then public.catalog_agent_external_evidence.status
      else excluded.status
    end,
    last_observed_at = v_now,
    updated_at = v_now
  returning * into v_row;

  return jsonb_build_object(
    'id', v_row.id,
    'normalized_text', v_row.normalized_text,
    'source_key', v_row.source_key,
    'evidence_type', v_row.evidence_type,
    'trust_level', v_row.trust_level,
    'confidence_score', v_row.confidence_score,
    'status', v_row.status
  );
end;
$$;

create or replace function public.get_catalog_agent_external_evidence_context(
  p_normalized_texts text[],
  p_limit_per_term integer default 4
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with requested_terms as (
    select distinct regexp_replace(lower(btrim(term)), '\s+', ' ', 'g') as normalized_text
    from unnest(coalesce(p_normalized_texts, array[]::text[])) as term
    where btrim(coalesce(term, '')) <> ''
  ),
  ranked as (
    select
      e.normalized_text,
      e.id,
      e.source_key,
      e.source_record_id,
      e.source_url,
      e.source_license,
      e.source_license_url,
      e.evidence_type,
      e.trust_level,
      e.confidence_score,
      e.language_code,
      e.canonical_label,
      e.aliases,
      e.evidence_summary,
      e.metadata,
      e.status,
      e.updated_at,
      row_number() over (
        partition by e.normalized_text
        order by
          case e.status
            when 'implemented' then 1
            when 'accepted' then 2
            when 'needs_review' then 3
            else 9
          end,
          case e.trust_level
            when 'high' then 1
            when 'medium' then 2
            else 3
          end,
          coalesce(e.confidence_score, 0) desc,
          e.updated_at desc
      ) as rn
    from public.catalog_agent_external_evidence e
    join requested_terms r
      on r.normalized_text = e.normalized_text
    where e.status in ('needs_review', 'accepted', 'implemented')
  ),
  limited as (
    select *
    from ranked
    where rn <= greatest(1, coalesce(p_limit_per_term, 4))
  ),
  term_map as (
    select
      normalized_text,
      jsonb_agg(
        jsonb_build_object(
          'id', id,
          'source_key', source_key,
          'source_record_id', source_record_id,
          'source_url', source_url,
          'source_license', source_license,
          'source_license_url', source_license_url,
          'evidence_type', evidence_type,
          'trust_level', trust_level,
          'confidence_score', confidence_score,
          'language_code', language_code,
          'canonical_label', canonical_label,
          'aliases', aliases,
          'evidence_summary', evidence_summary,
          'metadata', metadata,
          'status', status,
          'updated_at', updated_at
        )
        order by rn
      ) as evidence
    from limited
    group by normalized_text
  )
  select jsonb_build_object(
    'metadata', jsonb_build_object(
      'source', 'catalog_agent_external_evidence_context_v1',
      'terms_requested', (select count(*) from requested_terms),
      'terms_with_external_evidence', (select count(*) from term_map),
      'included_statuses', jsonb_build_array('implemented', 'accepted', 'needs_review')
    ),
    'runtime_instruction', jsonb_build_object(
      'policy', 'External catalog evidence is grounding evidence only. It can support identity, variant, taxonomy, synonym, or nutrition reasoning, but it is not Season catalog truth and must not bypass catalog_matcher, learning memory, deterministic validators, or apply gates.',
      'source_semantics', jsonb_build_object(
        'usda_fdc', 'high-trust nutrition and generic food identity evidence; strongest for nutrients, weaker for Italian culinary localization',
        'wikidata', 'CC0 multilingual/taxonomy evidence; useful for labels and identity hints, not sufficient alone for nutrition or apply',
        'foodon', 'ontology/taxonomy evidence; useful for family/classification, not sufficient alone for recipe-specific identity',
        'open_food_facts', 'ODbL branded/packaged product evidence; useful for packaged products, requires license-aware attribution and should be used cautiously',
        'manual_open_source_review', 'operator-reviewed external evidence summary'
      ),
      'status_semantics', jsonb_build_object(
        'implemented', 'external evidence already reflected in governed behavior; follow unless current evidence contradicts it',
        'accepted', 'reviewed grounding evidence; strongly prefer it as supporting evidence',
        'needs_review', 'unreviewed external evidence; use only as weak support or to ask better questions'
      )
    ),
    'term_external_evidence', coalesce(
      (select jsonb_object_agg(normalized_text, evidence) from term_map),
      '{}'::jsonb
    )
  );
$$;

revoke all on function public.upsert_catalog_agent_external_evidence(text, text, text, text, text, text, text, text, text, numeric, text, text, jsonb, jsonb, jsonb, text) from public, anon;
grant execute on function public.upsert_catalog_agent_external_evidence(text, text, text, text, text, text, text, text, text, numeric, text, text, jsonb, jsonb, jsonb, text) to authenticated, service_role;

revoke all on function public.get_catalog_agent_external_evidence_context(text[], integer) from public, anon;
grant execute on function public.get_catalog_agent_external_evidence_context(text[], integer) to authenticated, service_role;

comment on table public.catalog_agent_external_evidence is
  'Non-mutating external catalog/source evidence for Catalog Governance Agent grounding. Evidence is advisory and never catalog truth by itself.';

comment on function public.upsert_catalog_agent_external_evidence(text, text, text, text, text, text, text, text, text, numeric, text, text, jsonb, jsonb, jsonb, text) is
  'Catalog-admin/service-role helper to upsert license-aware external evidence. Does not mutate Season catalog identity.';

comment on function public.get_catalog_agent_external_evidence_context(text[], integer) is
  'Returns compact external evidence context for Catalog Governance Agent work items.';

commit;
