-- Consume the Giallo Zafferano ready queue created by the previous safe-promotion
-- step, then reconcile only exact-match safe recipe rows.
--
-- This migration is intentionally narrow and idempotent:
-- - source terms must still be unresolved Giallo Zafferano ingredients;
-- - drafts must already be status=ready and validated_ready=true;
-- - existing slugs are reused instead of duplicated;
-- - recipe rows are updated only through the existing safety preview signal.

create table if not exists public.catalog_ready_draft_creation_audit (
  id bigint generated by default as identity primary key,
  batch_id uuid not null,
  normalized_text text not null,
  ingredient_id uuid,
  ingredient_slug text,
  result_status text not null,
  detail text,
  created_new boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_catalog_ready_draft_creation_audit_created_at
  on public.catalog_ready_draft_creation_audit(created_at desc);

create index if not exists idx_catalog_ready_draft_creation_audit_result_status
  on public.catalog_ready_draft_creation_audit(result_status);

alter table public.catalog_ready_draft_creation_audit enable row level security;

revoke all on public.catalog_ready_draft_creation_audit from public, anon, authenticated;
grant all on public.catalog_ready_draft_creation_audit to service_role;

do $$
declare
  v_now timestamptz := now();
  v_creation_batch_id uuid := gen_random_uuid();
  v_reconciliation_batch_id uuid := gen_random_uuid();
  v_recipe_ingredients jsonb;
  v_old_ingredient jsonb;
  v_new_ingredient jsonb;
  v_new_ingredients jsonb;
  rec record;
begin
  create temp table _giallo_ready_drafts on commit drop as
  with unresolved_terms as (
    select distinct
      public.normalize_recipe_ingredient_text_for_matching(i.ingredient ->> 'name') as normalized_text
    from public.recipes r
    cross join lateral jsonb_array_elements(coalesce(r.ingredients::jsonb, '[]'::jsonb)) as i(ingredient)
    where r.source_name = 'ricette.giallozafferano.it'
      and nullif(trim(i.ingredient ->> 'ingredient_id'), '') is null
      and nullif(trim(i.ingredient ->> 'produce_id'), '') is null
      and nullif(trim(i.ingredient ->> 'basic_ingredient_id'), '') is null
  )
  select
    d.normalized_text,
    d.ingredient_type,
    d.canonical_name_it,
    d.canonical_name_en,
    d.suggested_slug,
    d.suggested_aliases,
    d.default_unit,
    d.supported_units,
    coalesce(d.is_seasonal, false) as is_seasonal,
    d.season_months,
    d.confidence_score,
    d.parent_candidate_slug,
    d.variant_kind,
    d.specificity_rank_suggestion
  from public.catalog_ingredient_enrichment_drafts d
  join unresolved_terms u
    on u.normalized_text = d.normalized_text
  where d.status = 'ready'
    and coalesce(d.validated_ready, false)
    and d.ingredient_type in ('basic', 'produce')
    and nullif(trim(coalesce(d.suggested_slug, '')), '') is not null
    and nullif(trim(coalesce(d.default_unit, '')), '') is not null
    and cardinality(coalesce(d.supported_units, '{}'::text[])) > 0;

  create temp table _giallo_created_ingredients (
    normalized_text text primary key,
    ingredient_id uuid not null,
    ingredient_slug text not null,
    created_new boolean not null default false
  ) on commit drop;

  insert into public.ingredients (
    slug,
    ingredient_type,
    is_seasonal,
    season_months,
    default_unit,
    supported_units,
    parent_ingredient_id,
    specificity_rank,
    variant_kind,
    created_at,
    updated_at
  )
  select
    d.suggested_slug,
    d.ingredient_type,
    d.is_seasonal,
    coalesce(d.season_months, '{}'::int[]),
    d.default_unit,
    d.supported_units,
    case
      when parent.id is not null
        and nullif(trim(coalesce(d.variant_kind, '')), '') is not null
        and coalesce(d.specificity_rank_suggestion, 0) >= 1
      then parent.id
      else null
    end as parent_ingredient_id,
    case
      when parent.id is not null
        and nullif(trim(coalesce(d.variant_kind, '')), '') is not null
        and coalesce(d.specificity_rank_suggestion, 0) >= 1
      then d.specificity_rank_suggestion
      else 0
    end as specificity_rank,
    case
      when parent.id is not null
        and nullif(trim(coalesce(d.variant_kind, '')), '') is not null
        and coalesce(d.specificity_rank_suggestion, 0) >= 1
      then lower(trim(d.variant_kind))
      else 'base'
    end as variant_kind,
    v_now,
    v_now
  from _giallo_ready_drafts d
  left join public.ingredients parent
    on parent.slug = nullif(lower(trim(coalesce(d.parent_candidate_slug, ''))), '')
  where not exists (
    select 1
    from public.ingredients i
    where i.slug = d.suggested_slug
  );

  insert into _giallo_created_ingredients (
    normalized_text,
    ingredient_id,
    ingredient_slug,
    created_new
  )
  select
    d.normalized_text,
    i.id,
    i.slug,
    not exists (
      select 1
      from public.catalog_candidate_decisions ccd
      where ccd.normalized_text = d.normalized_text
        and ccd.ingredient_id = i.id
        and ccd.action in ('create_ingredient_from_candidate', 'create_ingredient_from_candidate_existing')
    ) as created_new
  from _giallo_ready_drafts d
  join public.ingredients i
    on i.slug = d.suggested_slug
  on conflict (normalized_text) do nothing;

  insert into public.ingredient_localizations (
    ingredient_id,
    language_code,
    display_name,
    created_at,
    updated_at
  )
  select
    c.ingredient_id,
    l.language_code,
    l.display_name,
    v_now,
    v_now
  from _giallo_created_ingredients c
  join _giallo_ready_drafts d
    on d.normalized_text = c.normalized_text
  cross join lateral (
    values
      ('it'::text, nullif(trim(coalesce(d.canonical_name_it, '')), '')),
      ('en'::text, nullif(trim(coalesce(d.canonical_name_en, '')), ''))
  ) as l(language_code, display_name)
  where l.display_name is not null
  on conflict on constraint ingredient_localizations_pkey do update
  set
    display_name = excluded.display_name,
    updated_at = excluded.updated_at;

  insert into public.ingredient_aliases_v2 (
    ingredient_id,
    alias_text,
    normalized_alias_text,
    language_code,
    source,
    confidence,
    confidence_score,
    is_active,
    status,
    approval_source,
    approved_at,
    review_notes,
    created_at,
    updated_at
  )
  select
    c.ingredient_id,
    coalesce(nullif(trim(d.canonical_name_it), ''), d.normalized_text),
    d.normalized_text,
    'it',
    'catalog_enrichment',
    d.confidence_score,
    d.confidence_score,
    true,
    'approved',
    'llm_suggestion',
    v_now,
    'auto_created_from_giallozafferano_ready_enrichment_draft',
    v_now,
    v_now
  from _giallo_created_ingredients c
  join _giallo_ready_drafts d
    on d.normalized_text = c.normalized_text
  where not exists (
    select 1
    from public.ingredient_aliases_v2 a
    where a.normalized_alias_text = d.normalized_text
      and coalesce(a.is_active, true)
  );

  insert into public.custom_ingredient_observations (
    normalized_text,
    raw_examples,
    language_code,
    source,
    occurrence_count,
    status,
    first_seen_at,
    last_seen_at,
    updated_at
  )
  select
    d.normalized_text,
    jsonb_build_array(d.normalized_text),
    'it',
    'giallozafferano_ready_creation',
    1,
    'ingredient_created',
    v_now,
    v_now,
    v_now
  from _giallo_ready_drafts d
  on conflict (normalized_text) do update
  set
    status = 'ingredient_created',
    updated_at = excluded.updated_at;

  insert into public.catalog_candidate_decisions (
    normalized_text,
    action,
    ingredient_id,
    alias_text,
    language_code,
    confidence_score,
    reviewer_note,
    resulting_observation_status,
    resulting_alias_status,
    created_at,
    updated_at
  )
  select
    d.normalized_text,
    case when c.created_new then 'create_ingredient_from_candidate' else 'create_ingredient_from_candidate_existing' end,
    c.ingredient_id,
    coalesce(nullif(trim(d.canonical_name_it), ''), d.normalized_text),
    'it',
    d.confidence_score,
    'auto_created_from_giallozafferano_ready_enrichment_draft',
    'ingredient_created',
    'approved',
    v_now,
    v_now
  from _giallo_created_ingredients c
  join _giallo_ready_drafts d
    on d.normalized_text = c.normalized_text
  where not exists (
    select 1
    from public.catalog_candidate_decisions existing
    where existing.normalized_text = d.normalized_text
      and existing.ingredient_id = c.ingredient_id
      and existing.action in ('create_ingredient_from_candidate', 'create_ingredient_from_candidate_existing')
  );

  update public.catalog_ingredient_enrichment_drafts d
  set
    status = 'applied',
    needs_manual_review = false,
    reviewer_note = coalesce(nullif(trim(d.reviewer_note), '') || E'\n', '')
      || 'auto_applied_from_giallozafferano_ready_creation_batch',
    validated_ready = true,
    validated_errors = '[]'::jsonb,
    last_validated_at = v_now,
    updated_at = v_now
  from _giallo_created_ingredients c
  where c.normalized_text = d.normalized_text
    and d.status = 'ready';

  insert into public.catalog_ready_draft_creation_audit (
    batch_id,
    normalized_text,
    ingredient_id,
    ingredient_slug,
    result_status,
    detail,
    created_new
  )
  select
    v_creation_batch_id,
    c.normalized_text,
    c.ingredient_id,
    c.ingredient_slug,
    case when c.created_new then 'created' else 'reused_existing' end,
    'giallozafferano_ready_draft_creation',
    c.created_new
  from _giallo_created_ingredients c;

  for rec in
    select
      p.recipe_id,
      p.recipe_ingredient_row_id,
      p.ingredient_index,
      p.matched_ingredient_id,
      p.match_source
    from public.recipe_ingredient_reconciliation_safety_preview p
    join public.recipes r
      on r.id::text = p.recipe_id
    where r.source_name = 'ricette.giallozafferano.it'
      and p.safe_to_apply
      and p.match_source in ('approved_alias', 'canonical_localization')
    order by p.recipe_id asc, p.ingredient_index asc
  loop
    select r.ingredients::jsonb
    into v_recipe_ingredients
    from public.recipes r
    where r.id::text = rec.recipe_id
    for update;

    select e.elem
    into v_old_ingredient
    from jsonb_array_elements(v_recipe_ingredients) with ordinality as e(elem, ord)
    where e.ord = rec.ingredient_index;

    if v_old_ingredient is null then
      continue;
    end if;

    if nullif(trim(coalesce(v_old_ingredient ->> 'produce_id', '')), '') is not null
       or nullif(trim(coalesce(v_old_ingredient ->> 'basic_ingredient_id', '')), '') is not null
       or nullif(trim(coalesce(v_old_ingredient ->> 'ingredient_id', '')), '') is not null then
      continue;
    end if;

    v_new_ingredient :=
      (v_old_ingredient - 'produce_id' - 'basic_ingredient_id' - 'ingredient_id')
      || jsonb_build_object('ingredient_id', to_jsonb(rec.matched_ingredient_id::text));

    select jsonb_agg(
      case
        when e.ord = rec.ingredient_index then v_new_ingredient
        else e.elem
      end
      order by e.ord
    )
    into v_new_ingredients
    from jsonb_array_elements(v_recipe_ingredients) with ordinality as e(elem, ord);

    if v_new_ingredients is null then
      continue;
    end if;

    update public.recipes
    set ingredients = v_new_ingredients
    where id::text = rec.recipe_id;

    insert into public.recipe_ingredient_reconciliation_audit (
      batch_id,
      recipe_id,
      recipe_ingredient_row_id,
      ingredient_index,
      matched_ingredient_id,
      match_source,
      legacy_produce_id,
      legacy_basic_id,
      previous_ingredient_json,
      updated_ingredient_json,
      applied_at,
      mechanism,
      created_at,
      updated_at
    )
    values (
      v_reconciliation_batch_id,
      rec.recipe_id,
      rec.recipe_ingredient_row_id,
      rec.ingredient_index,
      rec.matched_ingredient_id,
      rec.match_source,
      null,
      null,
      v_old_ingredient,
      v_new_ingredient,
      v_now,
      'giallozafferano_ready_creation_safe_apply',
      v_now,
      v_now
    );
  end loop;
end;
$$;
