begin;

-- Service-role-safe auto-apply foundation for the Catalog Governance Agent.
--
-- This does not schedule autonomous work. It only creates a narrow mutation
-- path that future workers can use after deterministic validation has already
-- approved a low-risk, auto_apply_eligible proposal.

alter table public.ingredient_aliases_v2
  drop constraint if exists ingredient_aliases_v2_approval_source_check;

alter table public.ingredient_aliases_v2
  add constraint ingredient_aliases_v2_approval_source_check
  check (
    approval_source in (
      'manual',
      'import_observation',
      'llm_suggestion',
      'legacy_migration',
      'agent_auto_apply'
    )
  );

create table if not exists public.catalog_agent_apply_audit (
  id bigint generated by default as identity primary key,
  proposal_id bigint not null references public.catalog_agent_proposals(id) on delete cascade,
  run_id bigint references public.catalog_agent_runs(id) on delete set null,
  worker_job_id bigint references public.catalog_agent_worker_jobs(id) on delete set null,
  mutation_type text not null
    check (mutation_type in ('approve_alias', 'add_localization')),
  mutation_scope text not null
    check (mutation_scope in ('catalog_alias', 'ingredient_localization')),
  apply_mode text not null
    check (apply_mode in ('agent_service_role', 'catalog_admin')),
  actor_role text,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_ingredient_id uuid references public.ingredients(id) on delete set null,
  status text not null default 'applied'
    check (status in ('applied', 'reverted', 'revert_failed')),
  before_state jsonb not null default '{}'::jsonb
    check (jsonb_typeof(before_state) = 'object'),
  after_state jsonb not null default '{}'::jsonb
    check (jsonb_typeof(after_state) = 'object'),
  rollback_plan jsonb not null default '{}'::jsonb
    check (jsonb_typeof(rollback_plan) = 'object'),
  apply_note text,
  revert_reason text,
  applied_at timestamptz not null default now(),
  reverted_at timestamptz,
  reverted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_apply_audit_reverted_requires_time
    check (status <> 'reverted' or reverted_at is not null)
);

create unique index if not exists catalog_agent_apply_audit_proposal_unique_idx
  on public.catalog_agent_apply_audit(proposal_id);

create index if not exists catalog_agent_apply_audit_run_created_idx
  on public.catalog_agent_apply_audit(run_id, created_at desc)
  where run_id is not null;

create index if not exists catalog_agent_apply_audit_worker_created_idx
  on public.catalog_agent_apply_audit(worker_job_id, created_at desc)
  where worker_job_id is not null;

create index if not exists catalog_agent_apply_audit_status_created_idx
  on public.catalog_agent_apply_audit(status, created_at desc);

alter table public.catalog_agent_apply_audit enable row level security;

revoke all on table public.catalog_agent_apply_audit from public, anon, authenticated;
grant select on table public.catalog_agent_apply_audit to authenticated;
grant all on table public.catalog_agent_apply_audit to service_role;

drop policy if exists catalog_agent_apply_audit_catalog_admin_select
on public.catalog_agent_apply_audit;
create policy catalog_agent_apply_audit_catalog_admin_select
on public.catalog_agent_apply_audit
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace function public.apply_catalog_agent_low_risk_proposal(
  p_proposal_id bigint,
  p_worker_job_id bigint default null,
  p_apply_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), auth.role(), '');
  v_apply_mode text;
  v_row public.catalog_agent_proposals%rowtype;
  v_target public.ingredients%rowtype;
  v_alias_before public.ingredient_aliases_v2%rowtype;
  v_alias_after public.ingredient_aliases_v2%rowtype;
  v_existing_localization public.ingredient_localizations%rowtype;
  v_localization_after public.ingredient_localizations%rowtype;
  v_alias_text text;
  v_alias_normalized text;
  v_language_code text;
  v_localized_name text;
  v_now timestamptz := now();
  v_note text := nullif(btrim(coalesce(p_apply_note, '')), '');
  v_observation_before jsonb := 'null'::jsonb;
  v_observation_after jsonb := 'null'::jsonb;
  v_before_state jsonb := '{}'::jsonb;
  v_after_state jsonb := '{}'::jsonb;
  v_rollback_plan jsonb := '{}'::jsonb;
  v_audit_id bigint;
  v_decision_id bigint;
  v_result jsonb;
begin
  if v_role is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
    v_apply_mode := 'catalog_admin';
  else
    v_apply_mode := 'agent_service_role';
  end if;

  if p_proposal_id is null then
    raise exception 'proposal_id_required'
      using errcode = '22023';
  end if;

  select *
  into v_row
  from public.catalog_agent_proposals p
  where p.id = p_proposal_id
  for update;

  if not found then
    raise exception 'catalog_agent_proposal_not_found: %', p_proposal_id
      using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.catalog_agent_apply_audit a
    where a.proposal_id = v_row.id
      and a.status = 'applied'
  ) then
    raise exception 'proposal_already_has_active_apply_audit: %', v_row.id
      using errcode = '22023';
  end if;

  if v_row.status <> 'validated' then
    raise exception 'auto_apply_requires_validated_status: status=%', v_row.status
      using errcode = '22023';
  end if;

  if v_row.risk_level <> 'low' then
    raise exception 'auto_apply_requires_low_risk: risk_level=%', v_row.risk_level
      using errcode = '22023';
  end if;

  if not coalesce(v_row.auto_apply_eligible, false) then
    raise exception 'auto_apply_requires_auto_apply_eligible'
      using errcode = '22023';
  end if;

  if jsonb_typeof(v_row.validation_errors) <> 'array'
     or jsonb_array_length(v_row.validation_errors) <> 0 then
    raise exception 'auto_apply_requires_empty_validation_errors'
      using errcode = '22023';
  end if;

  if v_row.proposal_type not in ('approve_alias', 'add_localization') then
    raise exception 'auto_apply_unsupported_proposal_type: %', v_row.proposal_type
      using errcode = '22023';
  end if;

  if p_worker_job_id is not null and not exists (
    select 1
    from public.catalog_agent_worker_jobs j
    where j.id = p_worker_job_id
      and j.worker_name = 'low_risk_apply_batch'
  ) then
    raise exception 'auto_apply_worker_job_not_found_or_wrong_type: %', p_worker_job_id
      using errcode = '22023';
  end if;

  if v_row.target_ingredient_id is not null then
    select *
    into v_target
    from public.ingredients i
    where i.id = v_row.target_ingredient_id
    limit 1;
  elsif nullif(btrim(coalesce(v_row.target_slug, '')), '') is not null then
    select *
    into v_target
    from public.ingredients i
    where i.slug = btrim(v_row.target_slug)
    limit 1;
  end if;

  if v_target.id is null then
    raise exception 'auto_apply_target_required'
      using errcode = '22023';
  end if;

  if coalesce(v_target.quality_status, '') <> 'active' then
    raise exception 'auto_apply_target_not_active: %', v_target.slug
      using errcode = '22023';
  end if;

  select to_jsonb(o)
  into v_observation_before
  from public.custom_ingredient_observations o
  where o.normalized_text = v_row.normalized_text
  limit 1;

  if v_row.proposal_type = 'approve_alias' then
    v_alias_text := coalesce(
      nullif(btrim(coalesce(v_row.proposed_alias_text, '')), ''),
      nullif(btrim(coalesce(v_row.normalized_text, '')), '')
    );
    v_alias_normalized := lower(btrim(coalesce(v_alias_text, '')));

    if v_alias_normalized = '' then
      raise exception 'auto_apply_alias_text_required'
        using errcode = '22023';
    end if;

    select *
    into v_alias_before
    from public.ingredient_aliases_v2 a
    where a.normalized_alias_text = v_alias_normalized
      and coalesce(a.is_active, true)
    order by a.id desc
    limit 1;

    if v_alias_before.id is not null and v_alias_before.ingredient_id <> v_target.id then
      raise exception 'auto_apply_active_alias_conflict: %', v_alias_normalized
        using errcode = '23505';
    end if;

    if v_alias_before.id is null then
      insert into public.ingredient_aliases_v2 (
        ingredient_id,
        alias_text,
        normalized_alias_text,
        language_code,
        source,
        confidence,
        confidence_score,
        is_active,
        status,
        approval_source,
        approved_at,
        approved_by,
        review_notes,
        created_at,
        updated_at
      )
      values (
        v_target.id,
        v_alias_text,
        v_alias_normalized,
        nullif(lower(btrim(coalesce(v_row.proposed_language_code, ''))), ''),
        'catalog_agent',
        v_row.confidence_score,
        v_row.confidence_score,
        true,
        'approved',
        'agent_auto_apply',
        v_now,
        v_user,
        coalesce(v_note, 'Auto-applied from validated low-risk Catalog Governance Agent proposal.'),
        v_now,
        v_now
      )
      returning * into v_alias_after;

      v_rollback_plan := jsonb_build_object(
        'action', 'delete_inserted_alias',
        'alias_id', v_alias_after.id,
        'normalized_alias_text', v_alias_normalized
      );
    else
      update public.ingredient_aliases_v2 a
      set
        alias_text = v_alias_text,
        language_code = coalesce(nullif(lower(btrim(coalesce(v_row.proposed_language_code, ''))), ''), a.language_code),
        source = 'catalog_agent',
        confidence = coalesce(v_row.confidence_score, a.confidence),
        confidence_score = coalesce(v_row.confidence_score, a.confidence_score, a.confidence),
        is_active = true,
        status = 'approved',
        approval_source = 'agent_auto_apply',
        approved_at = coalesce(a.approved_at, v_now),
        approved_by = coalesce(v_user, a.approved_by),
        review_notes = coalesce(v_note, 'Auto-applied from validated low-risk Catalog Governance Agent proposal.'),
        updated_at = v_now
      where a.id = v_alias_before.id
      returning * into v_alias_after;

      v_rollback_plan := jsonb_build_object(
        'action', 'restore_previous_alias_row',
        'alias_id', v_alias_before.id,
        'normalized_alias_text', v_alias_normalized
      );
    end if;

    update public.custom_ingredient_observations o
    set
      status = 'resolved_alias',
      updated_at = v_now
    where o.normalized_text = v_row.normalized_text;

    select to_jsonb(o)
    into v_observation_after
    from public.custom_ingredient_observations o
    where o.normalized_text = v_row.normalized_text
    limit 1;

    insert into public.catalog_candidate_decisions (
      normalized_text,
      action,
      ingredient_id,
      alias_text,
      language_code,
      confidence_score,
      reviewer_note,
      reviewer_id,
      resulting_observation_status,
      resulting_alias_status,
      created_at,
      updated_at
    )
    values (
      v_row.normalized_text,
      'approve_alias',
      v_target.id,
      v_alias_text,
      nullif(lower(btrim(coalesce(v_row.proposed_language_code, ''))), ''),
      v_row.confidence_score,
      coalesce(v_note, 'Auto-applied from validated low-risk Catalog Governance Agent proposal.'),
      v_user,
      'resolved_alias',
      'approved',
      v_now,
      v_now
    )
    returning id into v_decision_id;

    v_before_state := jsonb_build_object(
      'alias_row', case when v_alias_before.id is null then null else to_jsonb(v_alias_before) end,
      'observation_row', v_observation_before
    );
    v_after_state := jsonb_build_object(
      'alias_row', to_jsonb(v_alias_after),
      'observation_row', v_observation_after,
      'catalog_candidate_decision_id', v_decision_id
    );
  elsif v_row.proposal_type = 'add_localization' then
    v_language_code := lower(btrim(coalesce(v_row.proposed_language_code, '')));
    v_localized_name := nullif(btrim(coalesce(v_row.proposed_localized_name, '')), '');

    if v_language_code = '' then
      raise exception 'auto_apply_language_code_required'
        using errcode = '22023';
    end if;

    if v_localized_name is null then
      raise exception 'auto_apply_localized_name_required'
        using errcode = '22023';
    end if;

    select *
    into v_existing_localization
    from public.ingredient_localizations l
    where l.ingredient_id = v_target.id
      and l.language_code = v_language_code
    limit 1;

    if v_existing_localization.ingredient_id is not null
       and lower(btrim(v_existing_localization.display_name)) <> lower(btrim(v_localized_name)) then
      raise exception 'auto_apply_target_localization_conflict: %', v_language_code
        using errcode = '23505';
    end if;

    if v_existing_localization.ingredient_id is null then
      insert into public.ingredient_localizations (
        ingredient_id,
        language_code,
        display_name,
        created_at,
        updated_at
      )
      values (
        v_target.id,
        v_language_code,
        v_localized_name,
        v_now,
        v_now
      )
      returning * into v_localization_after;

      v_rollback_plan := jsonb_build_object(
        'action', 'delete_inserted_localization',
        'ingredient_id', v_target.id,
        'language_code', v_language_code
      );
    else
      v_localization_after := v_existing_localization;
      v_rollback_plan := jsonb_build_object(
        'action', 'none_existing_same_localization',
        'ingredient_id', v_target.id,
        'language_code', v_language_code
      );
    end if;

    v_before_state := jsonb_build_object(
      'localization_row', case
        when v_existing_localization.ingredient_id is null then null
        else to_jsonb(v_existing_localization)
      end
    );
    v_after_state := jsonb_build_object(
      'localization_row', to_jsonb(v_localization_after)
    );
  end if;

  update public.catalog_agent_proposals p
  set
    status = 'auto_applied',
    applied_at = v_now,
    applied_by = v_user,
    updated_at = v_now
  where p.id = v_row.id
  returning * into v_row;

  insert into public.catalog_agent_apply_audit (
    proposal_id,
    run_id,
    worker_job_id,
    mutation_type,
    mutation_scope,
    apply_mode,
    actor_role,
    actor_user_id,
    target_ingredient_id,
    status,
    before_state,
    after_state,
    rollback_plan,
    apply_note,
    applied_at,
    created_at,
    updated_at
  )
  values (
    v_row.id,
    v_row.run_id,
    p_worker_job_id,
    v_row.proposal_type,
    case
      when v_row.proposal_type = 'approve_alias' then 'catalog_alias'
      else 'ingredient_localization'
    end,
    v_apply_mode,
    v_role,
    v_user,
    v_target.id,
    'applied',
    v_before_state,
    v_after_state,
    v_rollback_plan,
    v_note,
    v_now,
    v_now,
    v_now
  )
  returning id into v_audit_id;

  insert into public.catalog_agent_proposal_events (
    proposal_id,
    run_id,
    event_type,
    event_payload,
    created_by
  )
  values (
    v_row.id,
    v_row.run_id,
    'auto_apply_succeeded',
    jsonb_build_object(
      'apply_audit_id', v_audit_id,
      'worker_job_id', p_worker_job_id,
      'proposal_type', v_row.proposal_type,
      'target_ingredient_id', v_target.id,
      'apply_mode', v_apply_mode,
      'mutation_scope', case
        when v_row.proposal_type = 'approve_alias' then 'catalog_alias'
        else 'ingredient_localization'
      end,
      'rollback_action', v_rollback_plan->>'action'
    ),
    v_user
  );

  v_result := jsonb_build_object(
    'ok', true,
    'proposal_id', v_row.id,
    'run_id', v_row.run_id,
    'apply_audit_id', v_audit_id,
    'status', v_row.status,
    'mutation_type', v_row.proposal_type,
    'rollback_action', v_rollback_plan->>'action'
  );

  return v_result;
exception
  when others then
    if v_row.id is not null then
      update public.catalog_agent_proposals p
      set
        validation_errors = coalesce(p.validation_errors, '[]'::jsonb) || jsonb_build_array(
          public.catalog_agent_validation_error(
            'auto_apply_failed',
            sqlerrm,
            'error'
          )
        ),
        updated_at = now()
      where p.id = v_row.id;

      insert into public.catalog_agent_proposal_events (
        proposal_id,
        run_id,
        event_type,
        event_payload,
        created_by
      )
      values (
        v_row.id,
        v_row.run_id,
        'auto_apply_failed',
        jsonb_build_object(
          'error', sqlerrm,
          'sqlstate', sqlstate,
          'worker_job_id', p_worker_job_id,
          'apply_mode', coalesce(v_apply_mode, 'unknown'),
          'mutation_scope', 'auto_apply_guarded'
        ),
        v_user
      );
    end if;

    raise;
end;
$$;

create or replace function public.apply_catalog_agent_low_risk_proposal_batch(
  p_limit integer default 10,
  p_worker_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), auth.role(), '');
  v_limit integer := least(greatest(coalesce(p_limit, 10), 1), 25);
  v_proposal_id bigint;
  v_result jsonb;
  v_results jsonb := '[]'::jsonb;
  v_applied_count integer := 0;
  v_failed_count integer := 0;
begin
  if v_role is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  for v_proposal_id in
    select p.id
    from public.catalog_agent_proposals p
    where p.status = 'validated'
      and p.risk_level = 'low'
      and coalesce(p.auto_apply_eligible, false)
      and p.proposal_type in ('approve_alias', 'add_localization')
      and jsonb_typeof(p.validation_errors) = 'array'
      and jsonb_array_length(p.validation_errors) = 0
      and not exists (
        select 1
        from public.catalog_agent_apply_audit a
        where a.proposal_id = p.id
          and a.status = 'applied'
      )
    order by p.created_at asc, p.id asc
    limit v_limit
  loop
    begin
      v_result := public.apply_catalog_agent_low_risk_proposal(
        p_proposal_id => v_proposal_id,
        p_worker_job_id => p_worker_job_id,
        p_apply_note => 'Batch auto-apply from validated low-risk Catalog Governance Agent proposal.'
      );
      v_applied_count := v_applied_count + 1;
    exception
      when others then
        v_failed_count := v_failed_count + 1;
        v_result := jsonb_build_object(
          'ok', false,
          'proposal_id', v_proposal_id,
          'error', sqlerrm,
          'sqlstate', sqlstate
        );
    end;

    v_results := v_results || jsonb_build_array(v_result);
  end loop;

  return jsonb_build_object(
    'ok', true,
    'applied', v_applied_count,
    'failed', v_failed_count,
    'results', v_results
  );
end;
$$;

create or replace function public.rollback_catalog_agent_apply(
  p_apply_audit_id bigint,
  p_revert_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), auth.role(), '');
  v_audit public.catalog_agent_apply_audit%rowtype;
  v_current_alias jsonb;
  v_current_localization jsonb;
  v_before_alias jsonb;
  v_after_alias jsonb;
  v_before_observation jsonb;
  v_reason text := nullif(btrim(coalesce(p_revert_reason, '')), '');
begin
  if v_role is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  if p_apply_audit_id is null then
    raise exception 'apply_audit_id_required'
      using errcode = '22023';
  end if;

  if v_reason is null then
    raise exception 'revert_reason_required'
      using errcode = '22023';
  end if;

  select *
  into v_audit
  from public.catalog_agent_apply_audit a
  where a.id = p_apply_audit_id
  for update;

  if not found then
    raise exception 'catalog_agent_apply_audit_not_found: %', p_apply_audit_id
      using errcode = 'P0002';
  end if;

  if v_audit.status <> 'applied' then
    raise exception 'catalog_agent_apply_not_revertible: status=%', v_audit.status
      using errcode = '22023';
  end if;

  if v_audit.mutation_type = 'approve_alias' then
    v_before_alias := v_audit.before_state->'alias_row';
    v_after_alias := v_audit.after_state->'alias_row';
    v_before_observation := v_audit.before_state->'observation_row';

    select to_jsonb(a)
    into v_current_alias
    from public.ingredient_aliases_v2 a
    where a.id = (v_audit.rollback_plan->>'alias_id')::bigint
    limit 1;

    if v_current_alias is distinct from v_after_alias then
      raise exception 'rollback_current_alias_changed: %', v_audit.rollback_plan->>'alias_id'
        using errcode = '40001';
    end if;

    if v_audit.rollback_plan->>'action' = 'delete_inserted_alias' then
      delete from public.ingredient_aliases_v2 a
      where a.id = (v_audit.rollback_plan->>'alias_id')::bigint;
    elsif v_audit.rollback_plan->>'action' = 'restore_previous_alias_row' then
      update public.ingredient_aliases_v2 a
      set
        ingredient_id = (v_before_alias->>'ingredient_id')::uuid,
        alias_text = v_before_alias->>'alias_text',
        normalized_alias_text = v_before_alias->>'normalized_alias_text',
        language_code = v_before_alias->>'language_code',
        source = v_before_alias->>'source',
        confidence = nullif(v_before_alias->>'confidence', '')::double precision,
        confidence_score = nullif(v_before_alias->>'confidence_score', '')::double precision,
        is_active = coalesce((v_before_alias->>'is_active')::boolean, true),
        status = v_before_alias->>'status',
        approval_source = v_before_alias->>'approval_source',
        approved_at = nullif(v_before_alias->>'approved_at', '')::timestamptz,
        approved_by = nullif(v_before_alias->>'approved_by', '')::uuid,
        review_notes = v_before_alias->>'review_notes',
        created_at = (v_before_alias->>'created_at')::timestamptz,
        updated_at = (v_before_alias->>'updated_at')::timestamptz
      where a.id = (v_before_alias->>'id')::bigint;
    else
      raise exception 'rollback_unsupported_alias_action: %', v_audit.rollback_plan->>'action'
        using errcode = '22023';
    end if;

    if jsonb_typeof(v_before_observation) = 'object' and v_before_observation ? 'id' then
      update public.custom_ingredient_observations o
      set
        status = v_before_observation->>'status',
        updated_at = (v_before_observation->>'updated_at')::timestamptz
      where o.id = (v_before_observation->>'id')::bigint;
    end if;
  elsif v_audit.mutation_type = 'add_localization' then
    if v_audit.rollback_plan->>'action' = 'delete_inserted_localization' then
      select to_jsonb(l)
      into v_current_localization
      from public.ingredient_localizations l
      where l.ingredient_id = (v_audit.rollback_plan->>'ingredient_id')::uuid
        and l.language_code = v_audit.rollback_plan->>'language_code'
      limit 1;

      if v_current_localization is distinct from (v_audit.after_state->'localization_row') then
        raise exception 'rollback_current_localization_changed: %', v_audit.rollback_plan->>'language_code'
          using errcode = '40001';
      end if;

      delete from public.ingredient_localizations l
      where l.ingredient_id = (v_audit.rollback_plan->>'ingredient_id')::uuid
        and l.language_code = v_audit.rollback_plan->>'language_code';
    elsif v_audit.rollback_plan->>'action' = 'none_existing_same_localization' then
      null;
    else
      raise exception 'rollback_unsupported_localization_action: %', v_audit.rollback_plan->>'action'
        using errcode = '22023';
    end if;
  else
    raise exception 'rollback_unsupported_mutation_type: %', v_audit.mutation_type
      using errcode = '22023';
  end if;

  update public.catalog_agent_proposals p
  set
    status = 'validated',
    applied_at = null,
    applied_by = null,
    updated_at = now()
  where p.id = v_audit.proposal_id
    and p.status = 'auto_applied';

  update public.catalog_agent_apply_audit a
  set
    status = 'reverted',
    reverted_at = now(),
    reverted_by = v_user,
    revert_reason = v_reason,
    updated_at = now()
  where a.id = v_audit.id
  returning * into v_audit;

  insert into public.catalog_agent_proposal_events (
    proposal_id,
    run_id,
    event_type,
    event_payload,
    created_by
  )
  values (
    v_audit.proposal_id,
    v_audit.run_id,
    'auto_apply_rollback_succeeded',
    jsonb_build_object(
      'apply_audit_id', v_audit.id,
      'worker_job_id', v_audit.worker_job_id,
      'mutation_type', v_audit.mutation_type,
      'rollback_action', v_audit.rollback_plan->>'action',
      'revert_reason', v_reason
    ),
    v_user
  );

  return jsonb_build_object(
    'ok', true,
    'apply_audit_id', v_audit.id,
    'proposal_id', v_audit.proposal_id,
    'status', v_audit.status,
    'reverted_at', v_audit.reverted_at
  );
exception
  when others then
    if v_audit.id is not null then
      update public.catalog_agent_apply_audit a
      set
        status = 'revert_failed',
        revert_reason = coalesce(v_reason, sqlerrm),
        updated_at = now()
      where a.id = v_audit.id;

      insert into public.catalog_agent_proposal_events (
        proposal_id,
        run_id,
        event_type,
        event_payload,
        created_by
      )
      values (
        v_audit.proposal_id,
        v_audit.run_id,
        'auto_apply_rollback_failed',
        jsonb_build_object(
          'apply_audit_id', v_audit.id,
          'error', sqlerrm,
          'sqlstate', sqlstate,
          'rollback_action', v_audit.rollback_plan->>'action'
        ),
        v_user
      );
    end if;

    raise;
end;
$$;

create or replace view public.catalog_agent_auto_apply_audit_summary
with (security_invoker = true)
as
select
  date_trunc('day', applied_at)::date as day,
  count(*)::bigint as total_auto_apply_records,
  count(*) filter (where status = 'applied')::bigint as active_applies,
  count(*) filter (where status = 'reverted')::bigint as reverted_applies,
  count(*) filter (where status = 'revert_failed')::bigint as failed_reverts,
  count(*) filter (where mutation_type = 'approve_alias')::bigint as alias_applies,
  count(*) filter (where mutation_type = 'add_localization')::bigint as localization_applies
from public.catalog_agent_apply_audit
group by 1;

revoke all on function public.apply_catalog_agent_low_risk_proposal(bigint, bigint, text) from public, anon;
grant execute on function public.apply_catalog_agent_low_risk_proposal(bigint, bigint, text) to authenticated, service_role;

revoke all on function public.apply_catalog_agent_low_risk_proposal_batch(integer, bigint) from public, anon;
grant execute on function public.apply_catalog_agent_low_risk_proposal_batch(integer, bigint) to authenticated, service_role;

revoke all on function public.rollback_catalog_agent_apply(bigint, text) from public, anon;
grant execute on function public.rollback_catalog_agent_apply(bigint, text) to authenticated, service_role;

revoke all on public.catalog_agent_auto_apply_audit_summary from public, anon;
grant select on public.catalog_agent_auto_apply_audit_summary to authenticated, service_role;

comment on table public.catalog_agent_apply_audit is
  'Append-only audit and rollback ledger for low-risk Catalog Governance Agent auto-applies.';

comment on function public.apply_catalog_agent_low_risk_proposal(bigint, bigint, text) is
  'Applies one validated low-risk auto_apply_eligible Catalog Governance Agent proposal. Service-role safe, tightly scoped to alias/localization mutations with rollback audit.';

comment on function public.apply_catalog_agent_low_risk_proposal_batch(integer, bigint) is
  'Applies a bounded batch of validated low-risk auto_apply_eligible Catalog Governance Agent proposals. Intended for a future low_risk_apply_batch worker.';

comment on function public.rollback_catalog_agent_apply(bigint, text) is
  'Reverts one active Catalog Governance Agent auto-apply when the audited after-state has not changed since apply.';

comment on view public.catalog_agent_auto_apply_audit_summary is
  'Daily rollup of Catalog Governance Agent auto-apply audit and rollback status.';

commit;
