-- Minimal backend-first enrichment draft layer for Catalog Intelligence.
-- This adds admin-only draft storage + validation RPCs before canonical ingredient creation.

create or replace function public.catalog_enrichment_months_valid(
  p_months int[]
)
returns boolean
language sql
immutable
set search_path = public
as $$
  select coalesce(bool_and(m between 1 and 12), true)
  from unnest(coalesce(p_months, '{}'::int[])) as t(m);
$$;

create table if not exists public.catalog_ingredient_enrichment_drafts (
  id bigint generated by default as identity primary key,
  normalized_text text not null,
  status text not null default 'pending',
  ingredient_type text not null default 'unknown',
  canonical_name_it text,
  canonical_name_en text,
  suggested_slug text,
  suggested_aliases jsonb not null default '[]'::jsonb,
  default_unit text,
  supported_units text[] not null default '{}'::text[],
  is_seasonal boolean,
  season_months int[] not null default '{}'::int[],
  nutrition_fields jsonb not null default '{}'::jsonb,
  confidence_score double precision,
  needs_manual_review boolean not null default true,
  reasoning_summary text,
  reviewer_note text,
  validated_ready boolean not null default false,
  validated_errors jsonb not null default '[]'::jsonb,
  last_validated_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_ingredient_enrichment_drafts_normalized_text_key unique (normalized_text),
  constraint catalog_ingredient_enrichment_drafts_status_check
    check (status in ('pending', 'ready', 'rejected')),
  constraint catalog_ingredient_enrichment_drafts_type_check
    check (ingredient_type in ('produce', 'basic', 'unknown')),
  constraint catalog_ingredient_enrichment_drafts_confidence_check
    check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1)),
  constraint catalog_ingredient_enrichment_drafts_suggested_aliases_type_check
    check (jsonb_typeof(suggested_aliases) = 'array'),
  constraint catalog_ingredient_enrichment_drafts_nutrition_fields_type_check
    check (jsonb_typeof(nutrition_fields) = 'object'),
  constraint catalog_ingredient_enrichment_drafts_months_range_check
    check (public.catalog_enrichment_months_valid(season_months)),
  constraint catalog_ingredient_enrichment_drafts_normalized_text_fk
    foreign key (normalized_text)
    references public.custom_ingredient_observations(normalized_text)
    on delete cascade
);

create index if not exists catalog_ingredient_enrichment_drafts_status_idx
  on public.catalog_ingredient_enrichment_drafts(status);

create index if not exists catalog_ingredient_enrichment_drafts_type_idx
  on public.catalog_ingredient_enrichment_drafts(ingredient_type);

create index if not exists catalog_ingredient_enrichment_drafts_updated_at_idx
  on public.catalog_ingredient_enrichment_drafts(updated_at desc);

alter table if exists public.catalog_ingredient_enrichment_drafts enable row level security;

revoke all on public.catalog_ingredient_enrichment_drafts from anon, authenticated, public;
grant all on public.catalog_ingredient_enrichment_drafts to service_role;

create or replace function public.catalog_enrichment_validation_errors(
  p_ingredient_type text,
  p_status text,
  p_canonical_name_it text,
  p_canonical_name_en text,
  p_suggested_slug text,
  p_default_unit text,
  p_supported_units text[],
  p_is_seasonal boolean,
  p_season_months int[]
)
returns text[]
language plpgsql
stable
set search_path = public
as $$
declare
  v_errors text[] := '{}'::text[];
  v_type text := lower(trim(coalesce(p_ingredient_type, 'unknown')));
  v_status text := lower(trim(coalesce(p_status, 'pending')));
  v_name_it text := nullif(trim(coalesce(p_canonical_name_it, '')), '');
  v_name_en text := nullif(trim(coalesce(p_canonical_name_en, '')), '');
  v_slug text := nullif(trim(coalesce(p_suggested_slug, '')), '');
  v_default_unit text := nullif(lower(trim(coalesce(p_default_unit, ''))), '');
  v_supported_units text[] := coalesce(p_supported_units, '{}'::text[]);
  v_months int[] := coalesce(p_season_months, '{}'::int[]);
begin
  if v_status not in ('pending', 'ready', 'rejected') then
    v_errors := array_append(v_errors, 'invalid_status');
    return v_errors;
  end if;

  if v_type not in ('produce', 'basic', 'unknown') then
    v_errors := array_append(v_errors, 'invalid_ingredient_type');
    return v_errors;
  end if;

  if v_status <> 'ready' then
    return v_errors;
  end if;

  if v_type = 'unknown' then
    v_errors := array_append(v_errors, 'ready_requires_classified_ingredient_type');
  end if;

  if v_name_it is null and v_name_en is null then
    v_errors := array_append(v_errors, 'ready_requires_canonical_name');
  end if;

  if v_slug is null then
    v_errors := array_append(v_errors, 'ready_requires_suggested_slug');
  end if;

  if v_default_unit is null then
    v_errors := array_append(v_errors, 'ready_requires_default_unit');
  end if;

  if coalesce(array_length(v_supported_units, 1), 0) = 0 then
    v_errors := array_append(v_errors, 'ready_requires_supported_units');
  elsif v_default_unit is not null and not (v_default_unit = any(v_supported_units)) then
    v_errors := array_append(v_errors, 'default_unit_must_be_supported');
  end if;

  if exists (
    select 1
    from unnest(v_months) as m(month_value)
    where m.month_value < 1 or m.month_value > 12
  ) then
    v_errors := array_append(v_errors, 'season_months_out_of_range');
  end if;

  -- Product rule: produce requires explicit seasonality consideration.
  if v_type = 'produce' then
    if p_is_seasonal is null then
      v_errors := array_append(v_errors, 'produce_requires_is_seasonal_considered');
    elsif p_is_seasonal and coalesce(array_length(v_months, 1), 0) = 0 then
      v_errors := array_append(v_errors, 'produce_seasonal_requires_season_months');
    end if;
  end if;

  return v_errors;
end;
$$;

create or replace function public.upsert_catalog_ingredient_enrichment_draft(
  p_normalized_text text,
  p_status text default 'pending',
  p_ingredient_type text default 'unknown',
  p_canonical_name_it text default null,
  p_canonical_name_en text default null,
  p_suggested_slug text default null,
  p_suggested_aliases jsonb default '[]'::jsonb,
  p_default_unit text default null,
  p_supported_units text[] default null,
  p_is_seasonal boolean default null,
  p_season_months int[] default null,
  p_nutrition_fields jsonb default '{}'::jsonb,
  p_confidence_score double precision default null,
  p_needs_manual_review boolean default true,
  p_reasoning_summary text default null,
  p_reviewer_note text default null
)
returns table (
  normalized_text text,
  status text,
  ingredient_type text,
  validated_ready boolean,
  validation_errors text[]
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_user uuid := auth.uid();
  v_normalized text := lower(trim(coalesce(p_normalized_text, '')));
  v_status text := lower(trim(coalesce(p_status, 'pending')));
  v_type text := lower(trim(coalesce(p_ingredient_type, 'unknown')));
  v_slug text := nullif(lower(trim(coalesce(p_suggested_slug, ''))), '');
  v_default_unit text := nullif(lower(trim(coalesce(p_default_unit, ''))), '');
  v_name_it text := nullif(trim(coalesce(p_canonical_name_it, '')), '');
  v_name_en text := nullif(trim(coalesce(p_canonical_name_en, '')), '');
  v_supported_units text[] := coalesce(p_supported_units, case when v_default_unit is null then '{}'::text[] else array[v_default_unit]::text[] end);
  v_season_months int[] := coalesce(p_season_months, '{}'::int[]);
  v_aliases jsonb := coalesce(p_suggested_aliases, '[]'::jsonb);
  v_nutrition jsonb := coalesce(p_nutrition_fields, '{}'::jsonb);
  v_errors text[];
  v_is_ready boolean;
begin
  perform public.assert_catalog_admin(v_user);

  if v_normalized = '' then
    raise exception 'normalized_text is required';
  end if;

  if not exists (
    select 1
    from public.custom_ingredient_observations o
    where o.normalized_text = v_normalized
  ) then
    raise exception 'candidate not found for normalized_text: %', v_normalized;
  end if;

  if jsonb_typeof(v_aliases) <> 'array' then
    raise exception 'suggested_aliases must be a JSON array';
  end if;

  if jsonb_typeof(v_nutrition) <> 'object' then
    raise exception 'nutrition_fields must be a JSON object';
  end if;

  v_errors := public.catalog_enrichment_validation_errors(
    v_type,
    v_status,
    v_name_it,
    v_name_en,
    v_slug,
    v_default_unit,
    v_supported_units,
    p_is_seasonal,
    v_season_months
  );
  v_is_ready := coalesce(array_length(v_errors, 1), 0) = 0 and v_status = 'ready';

  if v_status = 'ready' and not v_is_ready then
    raise exception 'draft_not_ready: %', array_to_string(v_errors, ', ');
  end if;

  insert into public.catalog_ingredient_enrichment_drafts (
    normalized_text,
    status,
    ingredient_type,
    canonical_name_it,
    canonical_name_en,
    suggested_slug,
    suggested_aliases,
    default_unit,
    supported_units,
    is_seasonal,
    season_months,
    nutrition_fields,
    confidence_score,
    needs_manual_review,
    reasoning_summary,
    reviewer_note,
    validated_ready,
    validated_errors,
    last_validated_at,
    created_by,
    updated_by,
    reviewed_by,
    created_at,
    updated_at
  )
  values (
    v_normalized,
    v_status,
    v_type,
    v_name_it,
    v_name_en,
    v_slug,
    v_aliases,
    v_default_unit,
    v_supported_units,
    p_is_seasonal,
    v_season_months,
    v_nutrition,
    p_confidence_score,
    coalesce(p_needs_manual_review, true),
    nullif(trim(coalesce(p_reasoning_summary, '')), ''),
    nullif(trim(coalesce(p_reviewer_note, '')), ''),
    v_is_ready,
    to_jsonb(v_errors),
    v_now,
    v_user,
    v_user,
    case when v_status in ('ready', 'rejected') then v_user else null end,
    v_now,
    v_now
  )
  on conflict (normalized_text) do update
  set
    status = excluded.status,
    ingredient_type = excluded.ingredient_type,
    canonical_name_it = excluded.canonical_name_it,
    canonical_name_en = excluded.canonical_name_en,
    suggested_slug = excluded.suggested_slug,
    suggested_aliases = excluded.suggested_aliases,
    default_unit = excluded.default_unit,
    supported_units = excluded.supported_units,
    is_seasonal = excluded.is_seasonal,
    season_months = excluded.season_months,
    nutrition_fields = excluded.nutrition_fields,
    confidence_score = excluded.confidence_score,
    needs_manual_review = excluded.needs_manual_review,
    reasoning_summary = excluded.reasoning_summary,
    reviewer_note = excluded.reviewer_note,
    validated_ready = excluded.validated_ready,
    validated_errors = excluded.validated_errors,
    last_validated_at = excluded.last_validated_at,
    updated_by = excluded.updated_by,
    reviewed_by = case
      when excluded.status in ('ready', 'rejected') then excluded.updated_by
      else public.catalog_ingredient_enrichment_drafts.reviewed_by
    end,
    updated_at = excluded.updated_at;

  return query
  select
    d.normalized_text,
    d.status,
    d.ingredient_type,
    d.validated_ready,
    array(
      select jsonb_array_elements_text(d.validated_errors)
    ) as validation_errors
  from public.catalog_ingredient_enrichment_drafts d
  where d.normalized_text = v_normalized
  limit 1;
end;
$$;

create or replace function public.get_catalog_ingredient_enrichment_draft(
  p_normalized_text text
)
returns table (
  normalized_text text,
  status text,
  ingredient_type text,
  canonical_name_it text,
  canonical_name_en text,
  suggested_slug text,
  suggested_aliases jsonb,
  default_unit text,
  supported_units text[],
  is_seasonal boolean,
  season_months int[],
  nutrition_fields jsonb,
  confidence_score double precision,
  needs_manual_review boolean,
  reasoning_summary text,
  reviewer_note text,
  validated_ready boolean,
  validation_errors text[],
  last_validated_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_normalized text := lower(trim(coalesce(p_normalized_text, '')));
begin
  perform public.assert_catalog_admin(v_user);

  if v_normalized = '' then
    raise exception 'normalized_text is required';
  end if;

  return query
  select
    d.normalized_text,
    d.status,
    d.ingredient_type,
    d.canonical_name_it,
    d.canonical_name_en,
    d.suggested_slug,
    d.suggested_aliases,
    d.default_unit,
    d.supported_units,
    d.is_seasonal,
    d.season_months,
    d.nutrition_fields,
    d.confidence_score,
    d.needs_manual_review,
    d.reasoning_summary,
    d.reviewer_note,
    d.validated_ready,
    array(select jsonb_array_elements_text(d.validated_errors)) as validation_errors,
    d.last_validated_at,
    d.updated_at
  from public.catalog_ingredient_enrichment_drafts d
  where d.normalized_text = v_normalized
  limit 1;
end;
$$;

create or replace function public.validate_catalog_ingredient_enrichment_draft(
  p_normalized_text text
)
returns table (
  normalized_text text,
  status text,
  ingredient_type text,
  is_ready boolean,
  validation_errors text[]
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_normalized text := lower(trim(coalesce(p_normalized_text, '')));
  v_now timestamptz := now();
  v_errors text[];
  v_is_ready boolean;
begin
  perform public.assert_catalog_admin(v_user);

  if v_normalized = '' then
    raise exception 'normalized_text is required';
  end if;

  if not exists (
    select 1
    from public.catalog_ingredient_enrichment_drafts d
    where d.normalized_text = v_normalized
  ) then
    raise exception 'enrichment draft not found for normalized_text: %', v_normalized;
  end if;

  select public.catalog_enrichment_validation_errors(
      d.ingredient_type,
      d.status,
      d.canonical_name_it,
      d.canonical_name_en,
      d.suggested_slug,
      d.default_unit,
      d.supported_units,
      d.is_seasonal,
      d.season_months
    )
  into v_errors
  from public.catalog_ingredient_enrichment_drafts d
  where d.normalized_text = v_normalized
  limit 1;

  select (
      coalesce(array_length(v_errors, 1), 0) = 0
      and d.status = 'ready'
    )
  into v_is_ready
  from public.catalog_ingredient_enrichment_drafts d
  where d.normalized_text = v_normalized
  limit 1;

  update public.catalog_ingredient_enrichment_drafts as d
  set
    validated_ready = coalesce(v_is_ready, false),
    validated_errors = to_jsonb(coalesce(v_errors, '{}'::text[])),
    last_validated_at = v_now,
    updated_by = v_user,
    updated_at = v_now
  where d.normalized_text = v_normalized;

  return query
  select
    d.normalized_text,
    d.status,
    d.ingredient_type,
    d.validated_ready,
    array(select jsonb_array_elements_text(d.validated_errors)) as validation_errors
  from public.catalog_ingredient_enrichment_drafts d
  where d.normalized_text = v_normalized
  limit 1;
end;
$$;

revoke all on function public.catalog_enrichment_months_valid(int[]) from public;
grant execute on function public.catalog_enrichment_months_valid(int[]) to service_role;

revoke all on function public.catalog_enrichment_validation_errors(text, text, text, text, text, text, text[], boolean, int[]) from public;
grant execute on function public.catalog_enrichment_validation_errors(text, text, text, text, text, text, text[], boolean, int[]) to service_role;

revoke all on function public.upsert_catalog_ingredient_enrichment_draft(
  text, text, text, text, text, text, jsonb, text, text[], boolean, int[], jsonb, double precision, boolean, text, text
) from public;
grant execute on function public.upsert_catalog_ingredient_enrichment_draft(
  text, text, text, text, text, text, jsonb, text, text[], boolean, int[], jsonb, double precision, boolean, text, text
) to authenticated;
grant execute on function public.upsert_catalog_ingredient_enrichment_draft(
  text, text, text, text, text, text, jsonb, text, text[], boolean, int[], jsonb, double precision, boolean, text, text
) to service_role;

revoke all on function public.get_catalog_ingredient_enrichment_draft(text) from public;
grant execute on function public.get_catalog_ingredient_enrichment_draft(text) to authenticated;
grant execute on function public.get_catalog_ingredient_enrichment_draft(text) to service_role;

revoke all on function public.validate_catalog_ingredient_enrichment_draft(text) from public;
grant execute on function public.validate_catalog_ingredient_enrichment_draft(text) to authenticated;
grant execute on function public.validate_catalog_ingredient_enrichment_draft(text) to service_role;
