begin;

-- Level 6.0 foundation: scheduled dev autonomy needs a kill switch, daily
-- ceilings, and a durable digest before any scheduler is allowed to run.

create table if not exists public.catalog_agent_dev_schedule_config (
  environment text primary key
    check (environment in ('dev', 'staging', 'production')),
  enabled boolean not null default false,
  triage_enabled boolean not null default false,
  low_risk_dry_run_enabled boolean not null default true,
  low_risk_apply_enabled boolean not null default false,
  source_domain text,
  max_agent_runs_per_day integer not null default 3
    check (max_agent_runs_per_day between 0 and 24),
  max_worker_jobs_per_day integer not null default 5
    check (max_worker_jobs_per_day between 0 and 100),
  max_real_applies_per_day integer not null default 1
    check (max_real_applies_per_day between 0 and 20),
  max_llm_tokens_per_day integer not null default 80000
    check (max_llm_tokens_per_day between 0 and 1000000),
  max_estimated_cost_usd_per_day numeric(12, 6) not null default 1.000000
    check (max_estimated_cost_usd_per_day >= 0),
  stale_worker_minutes integer not null default 30
    check (stale_worker_minutes between 5 and 1440),
  anomaly_threshold_failed_runs integer not null default 0
    check (anomaly_threshold_failed_runs >= 0),
  anomaly_threshold_failed_worker_jobs integer not null default 0
    check (anomaly_threshold_failed_worker_jobs >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.catalog_agent_dev_schedule_config (
  environment,
  enabled,
  triage_enabled,
  low_risk_dry_run_enabled,
  low_risk_apply_enabled,
  notes
)
values (
  'dev',
  false,
  false,
  true,
  false,
  'Disabled by default. Enable only after dev operator review and with low-risk apply still gated.'
)
on conflict (environment) do nothing;

create table if not exists public.catalog_agent_daily_digests (
  id bigint generated by default as identity primary key,
  environment text not null
    check (environment in ('dev', 'staging', 'production')),
  report_date date not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  status text not null
    check (status in ('green', 'yellow', 'red')),
  anomaly_count integer not null default 0
    check (anomaly_count >= 0),
  summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(summary) = 'object'),
  anomalies jsonb not null default '[]'::jsonb
    check (jsonb_typeof(anomalies) = 'array'),
  recommended_next_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_daily_digests_environment_date_unique
    unique (environment, report_date)
);

create index if not exists catalog_agent_daily_digests_status_date_idx
  on public.catalog_agent_daily_digests(environment, status, report_date desc);

alter table public.catalog_agent_dev_schedule_config enable row level security;
alter table public.catalog_agent_daily_digests enable row level security;

revoke all on table public.catalog_agent_dev_schedule_config from public, anon, authenticated;
revoke all on table public.catalog_agent_daily_digests from public, anon, authenticated;

grant select on table public.catalog_agent_dev_schedule_config to authenticated;
grant select on table public.catalog_agent_daily_digests to authenticated;
grant all on table public.catalog_agent_dev_schedule_config to service_role;
grant all on table public.catalog_agent_daily_digests to service_role;

drop policy if exists catalog_agent_dev_schedule_config_catalog_admin_select
on public.catalog_agent_dev_schedule_config;
create policy catalog_agent_dev_schedule_config_catalog_admin_select
on public.catalog_agent_dev_schedule_config
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

drop policy if exists catalog_agent_daily_digests_catalog_admin_select
on public.catalog_agent_daily_digests;
create policy catalog_agent_daily_digests_catalog_admin_select
on public.catalog_agent_daily_digests
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

create or replace function public.catalog_agent_build_daily_digest(
  p_report_date date default current_date,
  p_environment text default 'dev'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_environment text := lower(btrim(coalesce(p_environment, 'dev')));
  v_report_date date := coalesce(p_report_date, current_date);
  v_window_start timestamptz := v_report_date::timestamptz;
  v_window_end timestamptz := (v_report_date + 1)::timestamptz;
  v_config public.catalog_agent_dev_schedule_config%rowtype;
  v_summary jsonb;
  v_anomalies jsonb := '[]'::jsonb;
  v_status text := 'green';
  v_recommended_next_action text := 'No action required.';
  v_failed_runs integer := 0;
  v_failed_worker_jobs integer := 0;
  v_stale_worker_jobs integer := 0;
  v_revert_failed integer := 0;
  v_total_tokens bigint := 0;
  v_estimated_cost numeric(12, 6) := 0;
  v_agent_runs integer := 0;
  v_worker_jobs integer := 0;
  v_real_applies integer := 0;
  v_digest public.catalog_agent_daily_digests%rowtype;
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  if v_environment not in ('dev', 'staging', 'production') then
    raise exception 'unsupported_catalog_agent_environment: %', p_environment
      using errcode = '22023';
  end if;

  select *
  into v_config
  from public.catalog_agent_dev_schedule_config c
  where c.environment = v_environment;

  if not found then
    insert into public.catalog_agent_dev_schedule_config (environment)
    values (v_environment)
    on conflict (environment) do nothing;

    select *
    into v_config
    from public.catalog_agent_dev_schedule_config c
    where c.environment = v_environment;
  end if;

  select
    count(*)::integer,
    count(*) filter (where status = 'failed')::integer
  into v_agent_runs, v_failed_runs
  from public.catalog_agent_runs r
  where r.environment = v_environment
    and r.created_at >= v_window_start
    and r.created_at < v_window_end;

  select
    count(*)::integer,
    count(*) filter (where status = 'failed')::integer,
    count(*) filter (
      where status in ('queued', 'running')
        and created_at < now() - make_interval(mins => coalesce(v_config.stale_worker_minutes, 30))
    )::integer
  into v_worker_jobs, v_failed_worker_jobs, v_stale_worker_jobs
  from public.catalog_agent_worker_jobs w
  where w.environment = v_environment
    and w.created_at >= v_window_start
    and w.created_at < v_window_end;

  select
    coalesce(sum(total_tokens), 0)::bigint,
    coalesce(sum(estimated_cost_usd), 0)::numeric(12, 6)
  into v_total_tokens, v_estimated_cost
  from public.catalog_ai_usage_events u
  where u.environment = v_environment
    and u.created_at >= v_window_start
    and u.created_at < v_window_end;

  select
    count(*) filter (where status = 'applied')::integer,
    count(*) filter (where status = 'revert_failed')::integer
  into v_real_applies, v_revert_failed
  from public.catalog_agent_apply_audit a
  join public.catalog_agent_proposals p on p.id = a.proposal_id
  join public.catalog_agent_runs r on r.id = p.run_id
  where r.environment = v_environment
    and a.created_at >= v_window_start
    and a.created_at < v_window_end;

  if v_failed_runs > coalesce(v_config.anomaly_threshold_failed_runs, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'failed_agent_runs',
      'severity', 'red',
      'count', v_failed_runs,
      'message', 'One or more catalog agent runs failed during the digest window.'
    ));
  end if;

  if v_failed_worker_jobs > coalesce(v_config.anomaly_threshold_failed_worker_jobs, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'failed_worker_jobs',
      'severity', 'red',
      'count', v_failed_worker_jobs,
      'message', 'One or more delegated worker jobs failed during the digest window.'
    ));
  end if;

  if v_stale_worker_jobs > 0 then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'stale_worker_jobs',
      'severity', 'yellow',
      'count', v_stale_worker_jobs,
      'message', 'Queued or running worker jobs are older than the configured stale-worker window.'
    ));
  end if;

  if v_agent_runs > coalesce(v_config.max_agent_runs_per_day, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'agent_run_ceiling_exceeded',
      'severity', 'red',
      'count', v_agent_runs,
      'limit', v_config.max_agent_runs_per_day,
      'message', 'Daily agent run ceiling was exceeded.'
    ));
  end if;

  if v_worker_jobs > coalesce(v_config.max_worker_jobs_per_day, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'worker_job_ceiling_exceeded',
      'severity', 'red',
      'count', v_worker_jobs,
      'limit', v_config.max_worker_jobs_per_day,
      'message', 'Daily worker job ceiling was exceeded.'
    ));
  end if;

  if v_real_applies > coalesce(v_config.max_real_applies_per_day, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'real_apply_ceiling_exceeded',
      'severity', 'red',
      'count', v_real_applies,
      'limit', v_config.max_real_applies_per_day,
      'message', 'Daily real apply ceiling was exceeded.'
    ));
  end if;

  if v_total_tokens > coalesce(v_config.max_llm_tokens_per_day, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'llm_token_ceiling_exceeded',
      'severity', 'red',
      'count', v_total_tokens,
      'limit', v_config.max_llm_tokens_per_day,
      'message', 'Daily LLM token ceiling was exceeded.'
    ));
  end if;

  if v_estimated_cost > coalesce(v_config.max_estimated_cost_usd_per_day, 0) then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'estimated_cost_ceiling_exceeded',
      'severity', 'red',
      'count', v_estimated_cost,
      'limit', v_config.max_estimated_cost_usd_per_day,
      'message', 'Daily estimated AI cost ceiling was exceeded.'
    ));
  end if;

  if v_revert_failed > 0 then
    v_anomalies := v_anomalies || jsonb_build_array(jsonb_build_object(
      'code', 'rollback_failure',
      'severity', 'red',
      'count', v_revert_failed,
      'message', 'At least one auto-apply rollback failed and requires immediate operator review.'
    ));
  end if;

  if exists (
    select 1
    from jsonb_array_elements(v_anomalies) a(item)
    where a.item->>'severity' = 'red'
  ) then
    v_status := 'red';
    v_recommended_next_action := 'Pause scheduled autonomy and review red anomalies before the next run.';
  elsif jsonb_array_length(v_anomalies) > 0 then
    v_status := 'yellow';
    v_recommended_next_action := 'Review yellow anomalies before increasing autonomy limits.';
  end if;

  v_summary := jsonb_build_object(
    'environment', v_environment,
    'report_date', v_report_date,
    'window_start', v_window_start,
    'window_end', v_window_end,
    'config', jsonb_build_object(
      'enabled', coalesce(v_config.enabled, false),
      'triage_enabled', coalesce(v_config.triage_enabled, false),
      'low_risk_dry_run_enabled', coalesce(v_config.low_risk_dry_run_enabled, false),
      'low_risk_apply_enabled', coalesce(v_config.low_risk_apply_enabled, false),
      'max_agent_runs_per_day', v_config.max_agent_runs_per_day,
      'max_worker_jobs_per_day', v_config.max_worker_jobs_per_day,
      'max_real_applies_per_day', v_config.max_real_applies_per_day,
      'max_llm_tokens_per_day', v_config.max_llm_tokens_per_day,
      'max_estimated_cost_usd_per_day', v_config.max_estimated_cost_usd_per_day
    ),
    'agent_runs', jsonb_build_object(
      'total', v_agent_runs,
      'failed', v_failed_runs,
      'by_status', coalesce((
        select jsonb_object_agg(status, count)
        from (
          select r.status, count(*)::integer
          from public.catalog_agent_runs r
          where r.environment = v_environment
            and r.created_at >= v_window_start
            and r.created_at < v_window_end
          group by r.status
        ) s
      ), '{}'::jsonb)
    ),
    'worker_jobs', jsonb_build_object(
      'total', v_worker_jobs,
      'failed', v_failed_worker_jobs,
      'stale', v_stale_worker_jobs,
      'by_status', coalesce((
        select jsonb_object_agg(status, count)
        from (
          select w.status, count(*)::integer
          from public.catalog_agent_worker_jobs w
          where w.environment = v_environment
            and w.created_at >= v_window_start
            and w.created_at < v_window_end
          group by w.status
        ) s
      ), '{}'::jsonb)
    ),
    'proposals', jsonb_build_object(
      'created', coalesce((
        select count(*)::integer
        from public.catalog_agent_proposals p
        join public.catalog_agent_runs r on r.id = p.run_id
        where r.environment = v_environment
          and p.created_at >= v_window_start
          and p.created_at < v_window_end
      ), 0),
      'by_status', coalesce((
        select jsonb_object_agg(status, count)
        from (
          select p.status, count(*)::integer
          from public.catalog_agent_proposals p
          join public.catalog_agent_runs r on r.id = p.run_id
          where r.environment = v_environment
            and p.created_at >= v_window_start
            and p.created_at < v_window_end
          group by p.status
        ) s
      ), '{}'::jsonb),
      'by_risk', coalesce((
        select jsonb_object_agg(risk_level, count)
        from (
          select p.risk_level, count(*)::integer
          from public.catalog_agent_proposals p
          join public.catalog_agent_runs r on r.id = p.run_id
          where r.environment = v_environment
            and p.created_at >= v_window_start
            and p.created_at < v_window_end
          group by p.risk_level
        ) s
      ), '{}'::jsonb),
      'low_risk_apply_ready', coalesce((
        select count(*)::integer
        from public.catalog_agent_proposals p
        join public.catalog_agent_runs r on r.id = p.run_id
        where r.environment = v_environment
          and p.status = 'validated'
          and p.risk_level = 'low'
          and p.auto_apply_eligible
      ), 0)
    ),
    'apply_audit', jsonb_build_object(
      'real_applies', v_real_applies,
      'rollback_failures', v_revert_failed,
      'by_status', coalesce((
        select jsonb_object_agg(status, count)
        from (
          select a.status, count(*)::integer
          from public.catalog_agent_apply_audit a
          join public.catalog_agent_proposals p on p.id = a.proposal_id
          join public.catalog_agent_runs r on r.id = p.run_id
          where r.environment = v_environment
            and a.created_at >= v_window_start
            and a.created_at < v_window_end
          group by a.status
        ) s
      ), '{}'::jsonb)
    ),
    'ai_usage', jsonb_build_object(
      'total_tokens', v_total_tokens,
      'estimated_cost_usd', v_estimated_cost,
      'by_function', coalesce((
        select jsonb_object_agg(function_name, totals)
        from (
          select
            u.function_name,
            jsonb_build_object(
              'calls', count(*)::integer,
              'total_tokens', coalesce(sum(u.total_tokens), 0)::bigint,
              'estimated_cost_usd', coalesce(sum(u.estimated_cost_usd), 0)::numeric(12, 6)
            ) as totals
          from public.catalog_ai_usage_events u
          where u.environment = v_environment
            and u.created_at >= v_window_start
            and u.created_at < v_window_end
          group by u.function_name
        ) s
      ), '{}'::jsonb)
    )
  );

  insert into public.catalog_agent_daily_digests (
    environment,
    report_date,
    window_start,
    window_end,
    status,
    anomaly_count,
    summary,
    anomalies,
    recommended_next_action,
    created_at,
    updated_at
  )
  values (
    v_environment,
    v_report_date,
    v_window_start,
    v_window_end,
    v_status,
    jsonb_array_length(v_anomalies),
    v_summary,
    v_anomalies,
    v_recommended_next_action,
    now(),
    now()
  )
  on conflict (environment, report_date) do update
  set
    window_start = excluded.window_start,
    window_end = excluded.window_end,
    status = excluded.status,
    anomaly_count = excluded.anomaly_count,
    summary = excluded.summary,
    anomalies = excluded.anomalies,
    recommended_next_action = excluded.recommended_next_action,
    updated_at = now()
  returning * into v_digest;

  return jsonb_build_object(
    'ok', true,
    'digest_id', v_digest.id,
    'environment', v_digest.environment,
    'report_date', v_digest.report_date,
    'status', v_digest.status,
    'anomaly_count', v_digest.anomaly_count,
    'recommended_next_action', v_digest.recommended_next_action,
    'summary', v_digest.summary,
    'anomalies', v_digest.anomalies
  );
end;
$$;

create or replace function public.catalog_agent_dev_schedule_guard(
  p_environment text default 'dev'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_environment text := lower(btrim(coalesce(p_environment, 'dev')));
  v_config public.catalog_agent_dev_schedule_config%rowtype;
  v_today date := current_date;
  v_window_start timestamptz := current_date::timestamptz;
  v_window_end timestamptz := (current_date + 1)::timestamptz;
  v_agent_runs integer := 0;
  v_worker_jobs integer := 0;
  v_real_applies integer := 0;
  v_total_tokens bigint := 0;
  v_estimated_cost numeric(12, 6) := 0;
  v_reasons text[] := array[]::text[];
begin
  if current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    perform public.assert_catalog_admin(v_user);
  end if;

  if v_environment <> 'dev' then
    return jsonb_build_object(
      'ok', false,
      'environment', v_environment,
      'reason', 'scheduled_autonomy_dev_only'
    );
  end if;

  select *
  into v_config
  from public.catalog_agent_dev_schedule_config c
  where c.environment = v_environment;

  if not found or not coalesce(v_config.enabled, false) then
    return jsonb_build_object(
      'ok', false,
      'environment', v_environment,
      'reason', 'schedule_disabled',
      'kill_switch', true
    );
  end if;

  select count(*)::integer
  into v_agent_runs
  from public.catalog_agent_runs r
  where r.environment = v_environment
    and r.created_at >= v_window_start
    and r.created_at < v_window_end;

  select count(*)::integer
  into v_worker_jobs
  from public.catalog_agent_worker_jobs w
  where w.environment = v_environment
    and w.created_at >= v_window_start
    and w.created_at < v_window_end;

  select count(*)::integer
  into v_real_applies
  from public.catalog_agent_apply_audit a
  join public.catalog_agent_proposals p on p.id = a.proposal_id
  join public.catalog_agent_runs r on r.id = p.run_id
  where r.environment = v_environment
    and a.status = 'applied'
    and a.created_at >= v_window_start
    and a.created_at < v_window_end;

  select
    coalesce(sum(total_tokens), 0)::bigint,
    coalesce(sum(estimated_cost_usd), 0)::numeric(12, 6)
  into v_total_tokens, v_estimated_cost
  from public.catalog_ai_usage_events u
  where u.environment = v_environment
    and u.created_at >= v_window_start
    and u.created_at < v_window_end;

  if v_agent_runs >= v_config.max_agent_runs_per_day then
    v_reasons := array_append(v_reasons, 'agent_run_limit_reached');
  end if;

  if v_worker_jobs >= v_config.max_worker_jobs_per_day then
    v_reasons := array_append(v_reasons, 'worker_job_limit_reached');
  end if;

  if v_real_applies >= v_config.max_real_applies_per_day then
    v_reasons := array_append(v_reasons, 'real_apply_limit_reached');
  end if;

  if v_total_tokens >= v_config.max_llm_tokens_per_day then
    v_reasons := array_append(v_reasons, 'llm_token_limit_reached');
  end if;

  if v_estimated_cost >= v_config.max_estimated_cost_usd_per_day then
    v_reasons := array_append(v_reasons, 'estimated_cost_limit_reached');
  end if;

  return jsonb_build_object(
    'ok', cardinality(v_reasons) = 0,
    'environment', v_environment,
    'report_date', v_today,
    'reasons', to_jsonb(v_reasons),
    'allowed', jsonb_build_object(
      'triage', coalesce(v_config.triage_enabled, false) and cardinality(v_reasons) = 0,
      'low_risk_dry_run', coalesce(v_config.low_risk_dry_run_enabled, false) and cardinality(v_reasons) = 0,
      'low_risk_apply', coalesce(v_config.low_risk_apply_enabled, false) and cardinality(v_reasons) = 0
    ),
    'usage', jsonb_build_object(
      'agent_runs', v_agent_runs,
      'worker_jobs', v_worker_jobs,
      'real_applies', v_real_applies,
      'total_tokens', v_total_tokens,
      'estimated_cost_usd', v_estimated_cost
    ),
    'limits', jsonb_build_object(
      'max_agent_runs_per_day', v_config.max_agent_runs_per_day,
      'max_worker_jobs_per_day', v_config.max_worker_jobs_per_day,
      'max_real_applies_per_day', v_config.max_real_applies_per_day,
      'max_llm_tokens_per_day', v_config.max_llm_tokens_per_day,
      'max_estimated_cost_usd_per_day', v_config.max_estimated_cost_usd_per_day
    )
  );
end;
$$;

create or replace view public.catalog_agent_dev_schedule_status
with (security_invoker = true)
as
select
  c.environment,
  c.enabled,
  c.triage_enabled,
  c.low_risk_dry_run_enabled,
  c.low_risk_apply_enabled,
  c.max_agent_runs_per_day,
  c.max_worker_jobs_per_day,
  c.max_real_applies_per_day,
  c.max_llm_tokens_per_day,
  c.max_estimated_cost_usd_per_day,
  d.report_date as latest_report_date,
  d.status as latest_digest_status,
  d.anomaly_count as latest_anomaly_count,
  d.recommended_next_action as latest_recommended_next_action,
  d.updated_at as latest_digest_updated_at
from public.catalog_agent_dev_schedule_config c
left join lateral (
  select *
  from public.catalog_agent_daily_digests d
  where d.environment = c.environment
  order by d.report_date desc
  limit 1
) d on true;

revoke all on function public.catalog_agent_build_daily_digest(date, text) from public, anon;
grant execute on function public.catalog_agent_build_daily_digest(date, text) to authenticated, service_role;

revoke all on function public.catalog_agent_dev_schedule_guard(text) from public, anon;
grant execute on function public.catalog_agent_dev_schedule_guard(text) to authenticated, service_role;

revoke all on public.catalog_agent_dev_schedule_status from public, anon;
grant select on public.catalog_agent_dev_schedule_status to authenticated, service_role;

comment on table public.catalog_agent_dev_schedule_config is
  'Kill switch and daily autonomy ceilings for the Catalog Governance Agent scheduler.';

comment on table public.catalog_agent_daily_digests is
  'Durable daily shift report for scheduled Catalog Governance Agent activity and anomalies.';

comment on function public.catalog_agent_build_daily_digest(date, text) is
  'Builds and stores the daily scheduled-autonomy digest with anomaly classification.';

comment on function public.catalog_agent_dev_schedule_guard(text) is
  'Returns whether scheduled dev autonomy is allowed under the kill switch and daily ceilings.';

comment on view public.catalog_agent_dev_schedule_status is
  'Read model for admin console schedule configuration and latest digest status.';

commit;
