-- Decouple scheduled autopilot invocation auth from the Edge Function's
-- SUPABASE_SERVICE_ROLE_KEY literal value.
--
-- The cron job invokes an Edge Function over pg_net. If Supabase rotates or
-- rehydrates function secrets differently, a still-configured cron token can
-- reach the function but fail the function's exact string comparison. Store
-- only a SHA-256 hash of the configured cron token and let the function verify
-- that token as an ops invocation secret.

create extension if not exists pgcrypto;

create table if not exists public.catalog_automation_invocation_tokens (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.catalog_automation_invocation_tokens enable row level security;

revoke all on public.catalog_automation_invocation_tokens from anon, authenticated;
revoke all on public.catalog_automation_invocation_tokens from public;
grant all on public.catalog_automation_invocation_tokens to service_role;

insert into public.catalog_automation_invocation_tokens (
  token_hash,
  label,
  is_active,
  created_at,
  updated_at
)
select
  encode(extensions.digest(convert_to(token.service_key, 'UTF8'), 'sha256'), 'hex') as token_hash,
  'dev_catalog_autopilot_v2_q6h_pg_net',
  true,
  now(),
  now()
from (
  select (regexp_match(command, '''apikey'',\s*''([^'']+)'''))[1] as service_key
  from cron.job
  where jobname = 'dev_catalog_autopilot_v2_q6h'
  limit 1
) token
where nullif(trim(token.service_key), '') is not null
on conflict (token_hash) do update
set
  label = excluded.label,
  is_active = true,
  updated_at = now();

create or replace function public.is_catalog_automation_invocation_token(
  p_token text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.catalog_automation_invocation_tokens t
    where t.token_hash = encode(extensions.digest(convert_to(coalesce(p_token, ''), 'UTF8'), 'sha256'), 'hex')
      and coalesce(t.is_active, true)
  );
$$;

revoke all on function public.is_catalog_automation_invocation_token(text) from public;
grant execute on function public.is_catalog_automation_invocation_token(text) to service_role;
