begin;

-- Catalog Agent 7.5: make lexical expansion and learning taxonomy governed data,
-- not hidden prompt/code exceptions.

create table if not exists public.catalog_agent_lexical_candidate_overrides (
  id bigint generated by default as identity primary key,
  source_term text not null,
  candidate_term text not null,
  expansion_source text not null default 'governed_override',
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_lexical_candidate_overrides_terms_not_blank
    check (length(btrim(source_term)) > 0 and length(btrim(candidate_term)) > 0),
  constraint catalog_agent_lexical_candidate_overrides_unique_active
    unique (source_term, candidate_term, expansion_source)
);

alter table public.catalog_agent_lexical_candidate_overrides enable row level security;

revoke all on public.catalog_agent_lexical_candidate_overrides from public, anon, authenticated;
grant select on public.catalog_agent_lexical_candidate_overrides to authenticated;
grant all privileges on public.catalog_agent_lexical_candidate_overrides to service_role;

drop policy if exists catalog_agent_lexical_candidate_overrides_admin_select
on public.catalog_agent_lexical_candidate_overrides;

create policy catalog_agent_lexical_candidate_overrides_admin_select
on public.catalog_agent_lexical_candidate_overrides
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

insert into public.catalog_agent_lexical_candidate_overrides (
  source_term,
  candidate_term,
  expansion_source,
  notes
)
values
  ('uovo', 'uova', 'governed_irregular_plural', 'Italian egg singular/plural lookup pair.'),
  ('uova', 'uovo', 'governed_irregular_singular', 'Italian egg plural/singular lookup pair.'),
  ('pane raffermo', 'pane', 'governed_preparation_state_base', 'Stale is a preparation/state adjective; use bread as target lookup.'),
  ('pane rafferma', 'pane', 'governed_preparation_state_base', 'Stale is a preparation/state adjective; use bread as target lookup.'),
  ('fiocchi d avena', 'fiocchi d''avena', 'governed_apostrophe_variant', 'Apostrophe/space spelling variant for oat flakes.'),
  ('fiocchi d''avena', 'fiocchi d avena', 'governed_apostrophe_variant', 'Apostrophe/space spelling variant for oat flakes.')
on conflict (source_term, candidate_term, expansion_source) do update
set
  notes = excluded.notes,
  is_active = true,
  updated_at = now();

alter table public.catalog_agent_learnings
drop constraint if exists catalog_agent_learnings_learning_type_check;

alter table public.catalog_agent_learnings
add constraint catalog_agent_learnings_learning_type_check
check (
  learning_type in (
    'human_rejection',
    'validator_failure',
    'manual_apply_failure',
    'policy_gap',
    'ambiguity',
    'duplicate_identity_risk',
    'prompt_improvement',
    'catalog_gap',
    'other',
    'alias_policy',
    'variant_policy',
    'state_vs_identity',
    'ambiguous_term',
    'worker_failure'
  )
);

create or replace function public.catalog_agent_lexical_candidate_terms(
  p_normalized_text text
)
returns table(term text, expansion_source text)
language sql
stable
set search_path = public
as $$
  with input as (
    select nullif(lower(trim(coalesce(p_normalized_text, ''))), '') as normalized_text
  ),
  generated as (
    select normalized_text as term, 'original'::text as expansion_source
    from input
    where normalized_text is not null

    union all

    select regexp_replace(normalized_text, '\s+(rafferm[oaie]|cotto|cotta|cotti|cotte|crudo|cruda|crudi|crude|tostato|tostata|tostati|tostate|grattugiato|grattugiata|grattugiati|grattugiate|tritato|tritata|tritati|tritate|tagliato|tagliata|tagliati|tagliate|bollito|bollita|bolliti|bollite|lessato|lessata|lessati|lessate|fresco|fresca|freschi|fresche)$', '') as term,
      'preparation_state_stripped'::text as expansion_source
    from input
    where normalized_text ~ '\s+(rafferm[oaie]|cotto|cotta|cotti|cotte|crudo|cruda|crudi|crude|tostato|tostata|tostati|tostate|grattugiato|grattugiata|grattugiati|grattugiate|tritato|tritata|tritati|tritate|tagliato|tagliata|tagliati|tagliate|bollito|bollita|bolliti|bollite|lessato|lessata|lessati|lessate|fresco|fresca|freschi|fresche)$'

    union all

    select regexp_replace(normalized_text, 'i$', 'o') as term,
      'italian_plural_i_to_o'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}i$'

    union all

    select regexp_replace(normalized_text, 'i$', 'e') as term,
      'italian_plural_i_to_e'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}i$'

    union all

    select regexp_replace(normalized_text, 'e$', 'a') as term,
      'italian_plural_e_to_a'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}e$'

    union all

    select regexp_replace(normalized_text, 'e$', 'o') as term,
      'italian_plural_e_to_o'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}e$'

    union all

    select regexp_replace(normalized_text, 'o$', 'i') as term,
      'italian_singular_o_to_i'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}o$'

    union all

    select regexp_replace(normalized_text, 'o$', 'a') as term,
      'italian_singular_o_to_a'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}o$'

    union all

    select regexp_replace(normalized_text, 'a$', 'e') as term,
      'italian_singular_a_to_e'::text as expansion_source
    from input
    where normalized_text ~ '.{3,}a$'

    union all

    select o.candidate_term as term, o.expansion_source
    from input i
    join public.catalog_agent_lexical_candidate_overrides o
      on o.source_term = i.normalized_text
     and o.is_active
  )
  select distinct
    nullif(trim(generated.term), '') as term,
    generated.expansion_source
  from generated
  where nullif(trim(generated.term), '') is not null
    and length(trim(generated.term)) >= 2;
$$;

comment on table public.catalog_agent_lexical_candidate_overrides is
  'Governed lookup expansions for Catalog Agent matcher context. These rows are advisory lookup hints and do not approve aliases or mutate catalog identity.';

comment on function public.catalog_agent_lexical_candidate_terms(text) is
  'Read-only deterministic term expansion for Catalog Agent candidate lookup. Uses morphology, preparation-state stripping, and governed overrides; it does not approve or mutate catalog data.';

create or replace function public.record_catalog_agent_learning(
  p_proposal_id bigint default null,
  p_run_id bigint default null,
  p_learning_type text default 'other',
  p_observed_problem text default null,
  p_severity text default 'medium',
  p_corrected_decision text default null,
  p_policy_implication text default null,
  p_evaluation_recommendation text default null,
  p_prompt_recommendation text default null,
  p_validator_recommendation text default null,
  p_source_event_id bigint default null,
  p_status text default 'needs_review'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_learning_type text := lower(btrim(coalesce(p_learning_type, 'other')));
  v_severity text := lower(btrim(coalesce(p_severity, 'medium')));
  v_status text := lower(btrim(coalesce(p_status, 'needs_review')));
  v_problem text := nullif(btrim(coalesce(p_observed_problem, '')), '');
  v_proposal public.catalog_agent_proposals%rowtype;
  v_run_id bigint := p_run_id;
  v_normalized_text text;
  v_original jsonb := '{}'::jsonb;
  v_learning_id bigint;
begin
  perform public.assert_catalog_admin(v_user);

  if v_learning_type not in (
    'human_rejection',
    'validator_failure',
    'manual_apply_failure',
    'policy_gap',
    'ambiguity',
    'duplicate_identity_risk',
    'prompt_improvement',
    'catalog_gap',
    'other',
    'alias_policy',
    'variant_policy',
    'state_vs_identity',
    'ambiguous_term',
    'worker_failure'
  ) then
    v_learning_type := 'other';
  end if;

  if v_severity not in ('low', 'medium', 'high', 'critical') then
    v_severity := 'medium';
  end if;

  if v_status not in ('draft', 'needs_review', 'accepted', 'rejected', 'implemented', 'superseded') then
    v_status := 'needs_review';
  end if;

  if p_proposal_id is not null then
    select *
    into v_proposal
    from public.catalog_agent_proposals p
    where p.id = p_proposal_id;

    if found then
      v_run_id := coalesce(v_run_id, v_proposal.run_id);
      v_normalized_text := v_proposal.normalized_text;
      v_original := jsonb_build_object(
        'proposal_id', v_proposal.id,
        'proposal_type', v_proposal.proposal_type,
        'normalized_text', v_proposal.normalized_text,
        'target_ingredient_id', v_proposal.target_ingredient_id,
        'target_slug', v_proposal.target_slug,
        'proposed_slug', v_proposal.proposed_slug,
        'proposed_alias_text', v_proposal.proposed_alias_text,
        'proposed_localized_name', v_proposal.proposed_localized_name,
        'proposed_language_code', v_proposal.proposed_language_code,
        'confidence_score', v_proposal.confidence_score,
        'risk_level', v_proposal.risk_level,
        'status', v_proposal.status,
        'rationale', v_proposal.rationale,
        'validation_errors', v_proposal.validation_errors
      );
    end if;
  end if;

  if v_problem is null then
    raise exception 'observed_problem_required'
      using errcode = '22023';
  end if;

  insert into public.catalog_agent_learnings (
    proposal_id,
    run_id,
    normalized_text,
    learning_type,
    severity,
    status,
    original_recommendation,
    observed_problem,
    corrected_decision,
    policy_implication,
    evaluation_recommendation,
    prompt_recommendation,
    validator_recommendation,
    source_event_id,
    created_by,
    created_at,
    updated_at
  )
  values (
    p_proposal_id,
    v_run_id,
    v_normalized_text,
    v_learning_type,
    v_severity,
    v_status,
    v_original,
    v_problem,
    nullif(btrim(coalesce(p_corrected_decision, '')), ''),
    nullif(btrim(coalesce(p_policy_implication, '')), ''),
    nullif(btrim(coalesce(p_evaluation_recommendation, '')), ''),
    nullif(btrim(coalesce(p_prompt_recommendation, '')), ''),
    nullif(btrim(coalesce(p_validator_recommendation, '')), ''),
    p_source_event_id,
    v_user,
    now(),
    now()
  )
  returning id into v_learning_id;

  return jsonb_build_object(
    'ok', true,
    'learning_id', v_learning_id,
    'proposal_id', p_proposal_id,
    'run_id', v_run_id,
    'learning_type', v_learning_type,
    'status', v_status
  );
end;
$$;

comment on function public.record_catalog_agent_learning(bigint, bigint, text, text, text, text, text, text, text, text, bigint, text) is
  'Records governed Catalog Governance Agent learning memory. Supports alias/variant/state/catalog-gap/worker learning types; does not mutate catalog truth.';

commit;
