begin;

-- Proposal-only foundation for the autonomous Catalog Governance Agent.
--
-- This migration intentionally does not add any LLM runtime, scheduler,
-- auto-apply behavior, or catalog mutation path. It only persists agent runs,
-- structured proposals, and proposal audit events so future workers can reason
-- without bypassing existing governed catalog RPCs.

create table if not exists public.catalog_agent_runs (
  id bigint generated by default as identity primary key,
  environment text not null default 'unknown'
    check (environment in ('local', 'dev', 'staging', 'production', 'unknown')),
  agent_name text not null default 'catalog-governance-agent',
  agent_version text not null,
  model text,
  prompt_version text,
  mode text not null default 'proposal_only'
    check (mode in ('proposal_only', 'validation', 'auto_apply', 'manual_replay')),
  source_domain text,
  input_snapshot_hash text,
  input_summary jsonb not null default '{}'::jsonb,
  status text not null default 'started'
    check (status in ('started', 'completed', 'failed', 'cancelled')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  summary jsonb not null default '{}'::jsonb,
  error_message text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_runs_finished_after_started
    check (finished_at is null or finished_at >= started_at)
);

create table if not exists public.catalog_agent_proposals (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.catalog_agent_runs(id) on delete cascade,
  proposal_type text not null
    check (
      proposal_type in (
        'approve_alias',
        'create_canonical',
        'add_localization',
        'merge_duplicate',
        'redirect_duplicate',
        'reconcile_recipe_ingredients',
        'ignore_noise',
        'needs_human_review'
      )
    ),
  normalized_text text not null check (length(btrim(normalized_text)) > 0),
  source_observation_ids bigint[] not null default '{}'::bigint[],
  target_ingredient_id uuid references public.ingredients(id) on delete set null,
  target_slug text,
  proposed_slug text,
  proposed_alias_text text,
  proposed_localized_name text,
  proposed_language_code text,
  proposed_parent_ingredient_id uuid references public.ingredients(id) on delete set null,
  proposed_specificity_rank smallint,
  proposed_variant_kind text,
  duplicate_ingredient_id uuid references public.ingredients(id) on delete set null,
  confidence_score double precision
    check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1)),
  risk_level text not null default 'unknown'
    check (risk_level in ('low', 'medium', 'high', 'critical', 'unknown')),
  auto_apply_eligible boolean not null default false,
  rationale text,
  evidence jsonb not null default '[]'::jsonb,
  blocking_questions jsonb not null default '[]'::jsonb,
  raw_agent_output jsonb,
  status text not null default 'draft'
    check (
      status in (
        'draft',
        'queued_for_validation',
        'validated',
        'auto_applied',
        'needs_human_review',
        'rejected',
        'failed_validation',
        'superseded'
      )
    ),
  validation_errors jsonb not null default '[]'::jsonb,
  applied_at timestamptz,
  applied_by uuid references auth.users(id) on delete set null,
  rejection_reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_agent_proposals_auto_apply_low_risk_only
    check (
      auto_apply_eligible = false
      or risk_level = 'low'
    ),
  constraint catalog_agent_proposals_applied_requires_status
    check (
      applied_at is null
      or status = 'auto_applied'
    )
);

create table if not exists public.catalog_agent_proposal_events (
  id bigint generated by default as identity primary key,
  proposal_id bigint references public.catalog_agent_proposals(id) on delete cascade,
  run_id bigint references public.catalog_agent_runs(id) on delete cascade,
  event_type text not null check (length(btrim(event_type)) > 0),
  event_payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint catalog_agent_proposal_events_has_parent
    check (proposal_id is not null or run_id is not null)
);

create index if not exists catalog_agent_runs_status_started_idx
  on public.catalog_agent_runs(status, started_at desc);

create index if not exists catalog_agent_runs_environment_started_idx
  on public.catalog_agent_runs(environment, started_at desc);

create index if not exists catalog_agent_proposals_run_id_idx
  on public.catalog_agent_proposals(run_id);

create index if not exists catalog_agent_proposals_status_created_idx
  on public.catalog_agent_proposals(status, created_at desc);

create index if not exists catalog_agent_proposals_type_risk_idx
  on public.catalog_agent_proposals(proposal_type, risk_level, auto_apply_eligible);

create index if not exists catalog_agent_proposals_normalized_text_idx
  on public.catalog_agent_proposals(normalized_text);

create index if not exists catalog_agent_proposals_target_ingredient_idx
  on public.catalog_agent_proposals(target_ingredient_id)
  where target_ingredient_id is not null;

create index if not exists catalog_agent_proposals_source_observation_ids_gin_idx
  on public.catalog_agent_proposals using gin(source_observation_ids);

create index if not exists catalog_agent_proposal_events_proposal_created_idx
  on public.catalog_agent_proposal_events(proposal_id, created_at desc)
  where proposal_id is not null;

create index if not exists catalog_agent_proposal_events_run_created_idx
  on public.catalog_agent_proposal_events(run_id, created_at desc)
  where run_id is not null;

alter table public.catalog_agent_runs enable row level security;
alter table public.catalog_agent_proposals enable row level security;
alter table public.catalog_agent_proposal_events enable row level security;

revoke all on table public.catalog_agent_runs from public, anon, authenticated;
revoke all on table public.catalog_agent_proposals from public, anon, authenticated;
revoke all on table public.catalog_agent_proposal_events from public, anon, authenticated;

grant select on table public.catalog_agent_runs to authenticated;
grant select on table public.catalog_agent_proposals to authenticated;
grant select on table public.catalog_agent_proposal_events to authenticated;

grant all on table public.catalog_agent_runs to service_role;
grant all on table public.catalog_agent_proposals to service_role;
grant all on table public.catalog_agent_proposal_events to service_role;

drop policy if exists catalog_agent_runs_catalog_admin_select on public.catalog_agent_runs;
create policy catalog_agent_runs_catalog_admin_select
on public.catalog_agent_runs
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

drop policy if exists catalog_agent_proposals_catalog_admin_select on public.catalog_agent_proposals;
create policy catalog_agent_proposals_catalog_admin_select
on public.catalog_agent_proposals
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

drop policy if exists catalog_agent_proposal_events_catalog_admin_select on public.catalog_agent_proposal_events;
create policy catalog_agent_proposal_events_catalog_admin_select
on public.catalog_agent_proposal_events
for select
to authenticated
using (public.is_catalog_admin(auth.uid()));

comment on table public.catalog_agent_runs is
  'Proposal-only audit record for bounded Catalog Governance Agent executions.';

comment on table public.catalog_agent_proposals is
  'Structured AI agent recommendations. Advisory only until validated/applied by governed backend RPCs.';

comment on table public.catalog_agent_proposal_events is
  'Append-only timeline for agent proposal lifecycle events.';

comment on column public.catalog_agent_proposals.auto_apply_eligible is
  'Advisory flag only. A future validator and existing governed RPCs must still approve/apply any action.';

commit;
