-- Backend-driven safe auto-localization for high-confidence localization-only cases.
-- This reduces manual operator toil while keeping strict safety and full auditability.

create table if not exists public.catalog_localization_auto_apply_audit (
  id bigint generated by default as identity primary key,
  normalized_text text not null,
  ingredient_id uuid,
  ingredient_slug text,
  language_code text not null,
  attempted_display_name text,
  result_status text not null,
  detail text,
  error_message text,
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists idx_catalog_localization_auto_apply_audit_created_at
  on public.catalog_localization_auto_apply_audit(created_at desc);

create index if not exists idx_catalog_localization_auto_apply_audit_result_status
  on public.catalog_localization_auto_apply_audit(result_status);

alter table public.catalog_localization_auto_apply_audit enable row level security;

revoke all on public.catalog_localization_auto_apply_audit from public, anon, authenticated;
grant all on public.catalog_localization_auto_apply_audit to service_role;

create or replace function public.auto_apply_safe_localizations(
  p_limit integer default 50,
  p_language_code text default 'it'
)
returns table (
  normalized_text text,
  canonical_candidate_ingredient_id uuid,
  canonical_candidate_slug text,
  language_code text,
  attempted_display_name text,
  result_status text,
  detail text,
  error_message text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_limit integer := greatest(1, least(coalesce(p_limit, 50), 500));
  v_language_code text := lower(trim(coalesce(p_language_code, 'it')));
  v_existing_display_name text;
  v_compact_normalized text;
  v_compact_slug text;
  v_compact_candidate_name text;
  v_is_high_confidence boolean;
  v_attempted_display_name text;
  v_status text;
  v_detail text;
  v_error text;
  v_apply_row record;
  r record;
begin
  perform public.assert_catalog_admin(v_user);

  if v_language_code = '' then
    v_language_code := 'it';
  end if;

  for r in
    select
      b.normalized_text,
      b.canonical_candidate_ingredient_id,
      b.canonical_candidate_slug,
      b.canonical_candidate_name,
      b.likely_fix_type,
      b.recommended_next_action,
      b.row_count,
      b.recipe_count,
      b.occurrence_count
    from public.catalog_coverage_blocker_terms b
    where b.likely_fix_type = 'localization'
      and b.canonical_candidate_ingredient_id is not null
    order by
      b.row_count desc,
      b.recipe_count desc,
      b.occurrence_count desc,
      b.normalized_text asc
    limit v_limit
  loop
    v_error := null;
    v_status := null;
    v_detail := null;

    begin
      normalized_text := trim(coalesce(r.normalized_text, ''));
      canonical_candidate_ingredient_id := r.canonical_candidate_ingredient_id;
      canonical_candidate_slug := r.canonical_candidate_slug;
      language_code := v_language_code;
      attempted_display_name := null;

      if normalized_text = '' then
        v_status := 'skipped';
        v_detail := 'invalid_normalized_text';
      else
        v_compact_normalized := regexp_replace(lower(normalized_text), '[^a-z0-9]+', '', 'g');
        v_compact_slug := regexp_replace(lower(trim(replace(coalesce(canonical_candidate_slug, ''), '_', ' '))), '[^a-z0-9]+', '', 'g');
        v_compact_candidate_name := regexp_replace(lower(trim(coalesce(r.canonical_candidate_name, ''))), '[^a-z0-9]+', '', 'g');

        -- Strict high-confidence gate:
        -- canonical target must be unambiguous and normalized text must exactly align
        -- with canonical slug text or canonical candidate display text (after normalization).
        v_is_high_confidence :=
          v_compact_normalized <> '' and (
            (v_compact_slug <> '' and v_compact_normalized = v_compact_slug) or
            (v_compact_candidate_name <> '' and v_compact_normalized = v_compact_candidate_name)
          );

        if not v_is_high_confidence then
          v_status := 'skipped';
          v_detail := 'low_confidence_localization_candidate';
        else
          if v_compact_candidate_name <> '' and v_compact_normalized = v_compact_candidate_name then
            v_attempted_display_name := nullif(trim(coalesce(r.canonical_candidate_name, '')), '');
          else
            v_attempted_display_name := nullif(trim(initcap(normalized_text)), '');
          end if;

          if v_attempted_display_name is null then
            v_attempted_display_name := nullif(trim(normalized_text), '');
          end if;

          select l.display_name
          into v_existing_display_name
          from public.ingredient_localizations l
          where l.ingredient_id = canonical_candidate_ingredient_id
            and l.language_code = v_language_code;

          if v_existing_display_name is not null then
            if lower(trim(v_existing_display_name)) = lower(trim(v_attempted_display_name)) then
              v_status := 'skipped';
              v_detail := 'already_exists';
            else
              v_status := 'skipped';
              v_detail := 'conflict_existing_language_localization';
            end if;
          else
            select *
            into v_apply_row
            from public.add_ingredient_localization(
              canonical_candidate_ingredient_id,
              v_attempted_display_name,
              v_language_code
            );

            if coalesce(v_apply_row.applied, false) then
              v_status := 'succeeded';
              v_detail := coalesce(v_apply_row.status::text, 'inserted');
            else
              v_status := 'skipped';
              v_detail := coalesce(v_apply_row.status::text, 'not_applied');
            end if;
          end if;
        end if;
      end if;
    exception when others then
      v_status := 'failed';
      v_detail := 'auto_localization_failed';
      v_error := sqlerrm;
      raise notice '[SEASON_CATALOG_AUTO_LOCALIZATION] normalized_text=% ingredient_id=% error=%', normalized_text, canonical_candidate_ingredient_id, v_error;
    end;

    attempted_display_name := v_attempted_display_name;
    result_status := coalesce(v_status, 'failed');
    detail := coalesce(v_detail, 'unknown');
    error_message := v_error;

    insert into public.catalog_localization_auto_apply_audit (
      normalized_text,
      ingredient_id,
      ingredient_slug,
      language_code,
      attempted_display_name,
      result_status,
      detail,
      error_message,
      actor_user_id
    ) values (
      coalesce(normalized_text, ''),
      canonical_candidate_ingredient_id,
      canonical_candidate_slug,
      language_code,
      attempted_display_name,
      result_status,
      detail,
      error_message,
      v_user
    );

    return next;
  end loop;

  return;
end;
$$;

revoke all on function public.auto_apply_safe_localizations(integer, text) from public;
grant execute on function public.auto_apply_safe_localizations(integer, text) to authenticated;
grant execute on function public.auto_apply_safe_localizations(integer, text) to service_role;
