-- Foundation for recurring unresolved/custom ingredient observation logging.
-- This supports future batch review/alias expansion without changing app flows.

create table if not exists public.custom_ingredient_observations (
  id bigint generated by default as identity primary key,
  normalized_text text not null,
  raw_examples jsonb not null default '[]'::jsonb,
  occurrence_count integer not null default 1 check (occurrence_count >= 1),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  language_code text,
  source text not null default 'manual',
  latest_recipe_id text,
  latest_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint custom_ingredient_observations_normalized_text_key unique (normalized_text)
);

create index if not exists custom_ingredient_observations_last_seen_idx
  on public.custom_ingredient_observations(last_seen_at desc);

create index if not exists custom_ingredient_observations_status_idx
  on public.custom_ingredient_observations(status);

create or replace function public.observe_custom_ingredient(
  p_normalized_text text,
  p_raw_example text default null,
  p_language_code text default null,
  p_source text default 'manual',
  p_latest_recipe_id text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_user uuid := auth.uid();
  v_normalized text := lower(trim(coalesce(p_normalized_text, '')));
  v_example text := nullif(trim(coalesce(p_raw_example, '')), '');
  v_language text := nullif(trim(coalesce(p_language_code, '')), '');
  v_source text := nullif(trim(coalesce(p_source, '')), '');
  v_latest_recipe_id text := nullif(trim(coalesce(p_latest_recipe_id, '')), '');
begin
  if v_normalized is null or v_normalized = '' then
    return;
  end if;

  insert into public.custom_ingredient_observations (
    normalized_text,
    raw_examples,
    occurrence_count,
    first_seen_at,
    last_seen_at,
    language_code,
    source,
    latest_recipe_id,
    latest_user_id,
    status,
    created_at,
    updated_at
  )
  values (
    v_normalized,
    case
      when v_example is null then '[]'::jsonb
      else jsonb_build_array(v_example)
    end,
    1,
    v_now,
    v_now,
    v_language,
    coalesce(v_source, 'manual'),
    v_latest_recipe_id,
    v_user,
    'new',
    v_now,
    v_now
  )
  on conflict (normalized_text) do update
  set occurrence_count = custom_ingredient_observations.occurrence_count + 1,
      last_seen_at = v_now,
      language_code = coalesce(v_language, custom_ingredient_observations.language_code),
      source = coalesce(v_source, custom_ingredient_observations.source),
      latest_recipe_id = coalesce(v_latest_recipe_id, custom_ingredient_observations.latest_recipe_id),
      latest_user_id = coalesce(v_user, custom_ingredient_observations.latest_user_id),
      raw_examples = case
        when v_example is null then custom_ingredient_observations.raw_examples
        when custom_ingredient_observations.raw_examples @> jsonb_build_array(v_example) then custom_ingredient_observations.raw_examples
        else custom_ingredient_observations.raw_examples || jsonb_build_array(v_example)
      end,
      updated_at = v_now;
end;
$$;

revoke all on function public.observe_custom_ingredient(text, text, text, text, text) from public;
grant execute on function public.observe_custom_ingredient(text, text, text, text, text) to authenticated;
grant execute on function public.observe_custom_ingredient(text, text, text, text, text) to service_role;
