-- Recovery path for unresolved ingredient observations already present in persisted recipes.
-- This adds an admin-guarded, idempotent backfill operation that reuses observe_custom_ingredient.

create table if not exists public.recipe_unresolved_ingredient_observation_recovery_audit (
  id bigint generated by default as identity primary key,
  recipe_id text not null,
  ingredient_index integer not null,
  normalized_text text not null,
  raw_example text,
  source text not null default 'import_recovery',
  status text not null default 'observed',
  error_message text,
  processed_at timestamptz not null default now(),
  processed_by uuid references auth.users(id) on delete set null,
  constraint recipe_unresolved_observation_recovery_unique
    unique (recipe_id, ingredient_index, normalized_text)
);

create index if not exists recipe_unresolved_observation_recovery_recipe_idx
  on public.recipe_unresolved_ingredient_observation_recovery_audit(recipe_id);

create index if not exists recipe_unresolved_observation_recovery_processed_idx
  on public.recipe_unresolved_ingredient_observation_recovery_audit(processed_at desc);

alter table if exists public.recipe_unresolved_ingredient_observation_recovery_audit enable row level security;
revoke all on public.recipe_unresolved_ingredient_observation_recovery_audit from anon, authenticated, public;
grant all on public.recipe_unresolved_ingredient_observation_recovery_audit to service_role;

create or replace function public.recover_unresolved_recipe_ingredient_observations(
  p_limit integer default 1000,
  p_recipe_ids text[] default null,
  p_source text default 'import_recovery'
)
returns table (
  recipe_id text,
  ingredient_index integer,
  normalized_text text,
  raw_example text,
  result_status text,
  detail text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_source text := nullif(trim(coalesce(p_source, '')), '');
  v_audit_id bigint;
  rec record;
begin
  perform public.assert_catalog_admin(v_user);

  for rec in
    with recipe_rows as (
      select
        r.id::text as recipe_id,
        i.ordinality::integer as ingredient_index,
        i.ingredient as ingredient_json,
        nullif(trim(coalesce(i.ingredient ->> 'name', '')), '') as raw_name,
        lower(trim(regexp_replace(coalesce(i.ingredient ->> 'name', ''), '\\s+', ' ', 'g'))) as normalized_name
      from public.recipes r
      cross join lateral jsonb_array_elements(coalesce(r.ingredients::jsonb, '[]'::jsonb)) with ordinality as i(ingredient, ordinality)
      where p_recipe_ids is null or r.id::text = any(p_recipe_ids)
    )
    select
      rr.recipe_id,
      rr.ingredient_index,
      rr.raw_name,
      rr.normalized_name
    from recipe_rows rr
    where rr.raw_name is not null
      and rr.normalized_name <> ''
      and nullif(trim(coalesce(rr.ingredient_json ->> 'produce_id', '')), '') is null
      and nullif(trim(coalesce(rr.ingredient_json ->> 'basic_ingredient_id', '')), '') is null
      and nullif(trim(coalesce(rr.ingredient_json ->> 'ingredient_id', '')), '') is null
    order by rr.recipe_id asc, rr.ingredient_index asc
    limit greatest(1, coalesce(p_limit, 1000))
  loop
    begin
      insert into public.recipe_unresolved_ingredient_observation_recovery_audit (
        recipe_id,
        ingredient_index,
        normalized_text,
        raw_example,
        source,
        status,
        processed_by,
        processed_at
      )
      values (
        rec.recipe_id,
        rec.ingredient_index,
        rec.normalized_name,
        rec.raw_name,
        coalesce(v_source, 'import_recovery'),
        'observed',
        v_user,
        now()
      )
      on conflict on constraint recipe_unresolved_observation_recovery_unique do nothing
      returning id into v_audit_id;

      if v_audit_id is null then
        recipe_id := rec.recipe_id;
        ingredient_index := rec.ingredient_index;
        normalized_text := rec.normalized_name;
        raw_example := rec.raw_name;
        result_status := 'skipped';
        detail := 'already_processed';
        return next;
        continue;
      end if;

      perform public.observe_custom_ingredient(
        p_normalized_text => rec.normalized_name,
        p_raw_example => rec.raw_name,
        p_language_code => null,
        p_source => coalesce(v_source, 'import_recovery'),
        p_latest_recipe_id => rec.recipe_id
      );

      recipe_id := rec.recipe_id;
      ingredient_index := rec.ingredient_index;
      normalized_text := rec.normalized_name;
      raw_example := rec.raw_name;
      result_status := 'observed';
      detail := 'ok';
      return next;
    exception
      when others then
        if v_audit_id is not null then
          update public.recipe_unresolved_ingredient_observation_recovery_audit a
          set
            status = 'failed',
            error_message = sqlerrm,
            processed_at = now(),
            processed_by = v_user
          where a.id = v_audit_id;
        end if;

        recipe_id := rec.recipe_id;
        ingredient_index := rec.ingredient_index;
        normalized_text := rec.normalized_name;
        raw_example := rec.raw_name;
        result_status := 'failed';
        detail := sqlerrm;
        return next;
    end;

    v_audit_id := null;
  end loop;
end;
$$;

revoke all on function public.recover_unresolved_recipe_ingredient_observations(integer, text[], text) from public;
grant execute on function public.recover_unresolved_recipe_ingredient_observations(integer, text[], text) to authenticated;
grant execute on function public.recover_unresolved_recipe_ingredient_observations(integer, text[], text) to service_role;
