-- Temporary debug instrumentation tables for catalog automation/enrichment tracing.
-- Additive only. Safe to remove later once runtime issues are resolved.

create table if not exists public.catalog_function_debug_runs (
  run_id uuid primary key default gen_random_uuid(),
  function_name text not null,
  mode text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.catalog_function_debug_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.catalog_function_debug_runs(run_id) on delete cascade,
  function_name text not null,
  stage text not null,
  tracked_term text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists catalog_function_debug_runs_created_at_idx
  on public.catalog_function_debug_runs(created_at desc);

create index if not exists catalog_function_debug_runs_function_name_idx
  on public.catalog_function_debug_runs(function_name, created_at desc);

create index if not exists catalog_function_debug_events_run_id_created_at_idx
  on public.catalog_function_debug_events(run_id, created_at asc);

create index if not exists catalog_function_debug_events_function_stage_idx
  on public.catalog_function_debug_events(function_name, stage, created_at desc);

create index if not exists catalog_function_debug_events_tracked_term_idx
  on public.catalog_function_debug_events(tracked_term, created_at desc)
  where tracked_term is not null;

alter table if exists public.catalog_function_debug_runs disable row level security;
alter table if exists public.catalog_function_debug_events disable row level security;

revoke all on public.catalog_function_debug_runs from public, anon, authenticated;
revoke all on public.catalog_function_debug_events from public, anon, authenticated;
grant all on public.catalog_function_debug_runs to service_role;
grant all on public.catalog_function_debug_events to service_role;

